### ISSUE TITLE
latex_engine indenting

### ISSUE THREAD

**Issue by ericpgreen** [rstudio/rmarkdown#1019]
I posted a [question to SO](http://stackoverflow.com/questions/43376605/rmarkdown-pdf-font-not-available) about a problem I was having specifying fonts in yaml, and a commenter suggested changing the indentation to:

```
---
title: "My Title"
header-includes:
    - \usepackage[sfdefault]{roboto}
    - \usepackage[T1]{fontenc}
output:
    pdf_document:
    latex_engine: xelatex
mainfont: roboto
---
```

Originally I put `latex_engine` as the third level based on the documentation [here](http://rmarkdown.rstudio.com/pdf_document_format.html#latex_engine).
