### ISSUE TITLE
github_document(): headers with non-ASCII text don't work in TOC

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rmarkdown#1048]
Given a document with contents like:

```
---
title: "Link test"
output:
    github_document:
        toc: true
        toc_depth: 3
---

## Datensätze
```

A Markdown file with contents like this is generated:

```
Link test
================

-   [Datensätze](#datensatze)

Datensätze
----------
```

However, because the link has been ASCII-ified while the actual title text has not, the link no longer works correctly when rendered by GitHub. It seems like there's two solutions here:

1. Add some attributes that explicitly declare the href / id on the actual title text,
2. Avoid ASCII-ifying in the TOC for `github_document()`.
