### ISSUE TITLE
Don't rearrange the yaml

### ISSUE THREAD

**Issue by jennybc** [rstudio/rmarkdown#1054]
I have an Rmd that, sadly, must have two output formats. Here's the yaml, arranged in what I think is a very sensible way:

``` yaml
---
title: "Excuse me, do you have a moment to talk about version control?"
authors:
- name: Jennifer Bryan
  affiliation: |
    RStudio and the Department of Statistics, University of British Columbia
  thanks: |
    The author gratefully acknowledges the constructive feedback from reviewers
    Nicholas Horton and Colin Rundel.
blinded: 0
output:
  rticles::asa_article: null
  github_document:
    toc: yes
keywords: version control
abstract: Abstract abstract abstract.
bibliography: git-github-for-stats.bib
---
```

As I ping-pong between rendering to the two formats, it seems my yaml gets constantly re-written -- re-ordered, really. This causes lots of low value diffs and I find myself constantly scrutinizing them, making sure it's just the usual churn, then discarding those changes.

Here's a recent example:

<img width="773" alt="screen shot 2017-05-18 at 5 18 05 pm" src="https://cloud.githubusercontent.com/assets/599454/26228373/09f28e4e-3bee-11e7-9c03-33306cef0274.png">

If this is functional, then I guess it must be kept. But if its inessential, can the yaml be left alone? Or is there anything I can do to prevent this myself?
