### ISSUE TITLE
Error with long title with colon when changing output types

### ISSUE THREAD

**Issue by roliveros-ramos** [rstudio/rmarkdown#1089]
When I tried to knit the following rmarkdown file, it works:

```
---
title: 'Title to reproduce the error needs to be long enough to reach more than the second line: some more words'
author: The author
output:
  pdf_document: default
  word_document: default
---


## R Markdown

This is an R Markdown document. 

```
But if a go to the knit button and change the option to "Knit to word" the yaml header is reparsed and double quotes are added improperly:

```
---
title: "'Title to reproduce the error needs to be long enough to reach more than the"
  second line: some more words'
author: "The author"
output:
  word_document: default
  pdf_document: default
---

## R Markdown

This is an R Markdown document. 
```

This produce an obvious error.  I tried with different quotes (double, simple) and no quotes in title and the same happens.

The error:

> Error in yaml::yaml.load(enc2utf8(string), ...) : 
>   Parser error: while parsing a block mapping at line 1, column 1did not find expected key at line 2, column 3
> Calls: <Anonymous> ... yaml_load_utf8 -> mark_utf8 -> <Anonymous> -> .Call
> Ejecución interrumpida
> 

`sessionInfo()`

> R version 3.4.0 (2017-04-21)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows >= 8 x64 (build 9200)
> 
> Matrix products: default
> 
> locale:
> [1] LC_COLLATE=Spanish_Spain.1252 
> [2] LC_CTYPE=Spanish_Spain.1252   
> [3] LC_MONETARY=Spanish_Spain.1252
> [4] LC_NUMERIC=C                  
> [5] LC_TIME=Spanish_Spain.1252    
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets 
> [6] methods   base     
> 
> loaded via a namespace (and not attached):
>  [1] compiler_3.4.0  backports_1.0.5 magrittr_1.5   
>  [4] rprojroot_1.2   formatR_1.4     htmltools_0.3.5
>  [7] tools_3.4.0     base64enc_0.1-3 yaml_2.1.13    
> [10] Rcpp_0.12.8     stringi_1.1.1   rmarkdown_1.4  
> [13] knitr_1.14      jsonlite_1.0    stringr_1.1.0  
> [16] digest_0.6.10   evaluate_0.9
