### ISSUE TITLE
Allow parametized argument in logo YAML

### ISSUE THREAD

**Issue by stephLH** [rstudio/rmarkdown#1091]
Is it possible to parametize the logo in a ioslides markdown document ?

```
params:
  logo_path: "logo_path"
title: "title"
output: 
  ioslides_presentation:
    logo: "`r params$logo_path`"
```
