### ISSUE TITLE
Is it possible to use URLs in YAML front matter?

### ISSUE THREAD

**Issue by jzadra** [rstudio/rmarkdown#1102]
Is it possible to use a url in the YAML front matter for a docx styles document?

ie:
```
---
title: "Title"
author: "Author"
mainfont: Roboto
output:
  word_document:
    reference_docx: https://github.com/mygithub/myrepo/blob/master/template_files/report_template/mystyles.docx?raw=true
---
```

The above code fails:

```
pandoc: https://github.com/Sorenson-Impact/SI_Project_Template/blob/master/template_files/report_template/mystyles.docx?raw=true: openBinaryFile: does not exist (No such file or directory)
Error: pandoc document conversion failed with error 1
```
Enclosing the URL in quotes also fails.
