### ISSUE TITLE
Support for multiple output types of the same generic format?

### ISSUE THREAD

**Issue by cboettig** [rstudio/rmarkdown#113]
The current structure of the render function assumes that while a user may want to generate multiple different outputs from the same source, that user would only want one `html_document`, one `pdf_document`, etc.  

Having used this same workflow for some time (via pandoc and Make), I find that I often want multiple outputs of the same type. For instance, I may have one `pdf_document` in which the pandoc options are configured the way a journal insists upon for preprints and another to actually look pretty.  Hacking out my own [custom format](http://rmarkdown.rstudio.com/developer_custom_formats.html) seems rather silly when all I want is something with, say, two different templates like this:

``` yaml
output:
  pdf_document:
    template: pretty_template.tex

  pdf_document_for_review:
    keep_tex: true
    template: stupid_1990s_compatible_template.tex
```

Would it be reasonable to support multiple output formats of the same type by separating the name of the desired output (e.g. `pdf_document`) from the definition? Perhaps something like:

``` yaml
output:
  my_custom_output:
    format: pdf_document
    ...
```

**Comment by yihui** [comment]
@cboettig I think this issue should be much easier to solve than you imagined. You can create a simple wrapper of `pdf_document` like this:

```r
my_custom_output = function(..., ext = ".pdf") {
  fmt = rmarkdown::pdf_document(...)
  fmt$pandoc$ext = ext
  fmt
}
```

For your journal paper, you only need to provide a different filename extension. Strictly speaking, it is not an extension but a _suffix_ of the filename, e.g.

```yaml
output:
  MyPackage::my_custom_output:
    ext: _for_review.pdf
    keep_tex: true
    template: stupid_1990s_compatible_template.tex
```

Then `render("foo.Rmd", "MyPackage::my_custom_output")` should generate `foo_for_review.pdf`.

In general, I think it is a good idea to be able to generate multiple output files of the same type (e.g. PDF), but the key problem is that we have to be careful that one PDF output file does not overwrite the other. That is, different PDF output formats should generate PDF files of different filenames. Unfortunately, you cannot really specify the filename for an output format. The only way to avoid filename conflicts that I can think of is what I mentioned above: use different filename suffixes.
