### ISSUE TITLE
yaml package crashes with empty object input

### ISSUE THREAD

**Issue by jjallaire** [rstudio/rmarkdown#12]
The following causes the yaml parser to crash:

``` yaml
title: "Document Title"
output:
   html_document:
```
