### ISSUE TITLE
No toc generated with output: md_document

### ISSUE THREAD

**Issue by stla** [rstudio/rmarkdown#1216]
Hello,

 I've tried the latest CRAN version and the dev version. While setting `toc: true` for a `md_document`, the table of contents is not generated.

```
---
title: "No toc"
author: "Stéphane Laurent"
date: "12 décembre 2017"
output:
  md_document:
    toc: true
    variant: markdown
    preserve_yaml: true
---


# Part 1

This is an R Markdown document. 

# Part 2

You can also embed plots.
```
