### ISSUE TITLE
phonetic symbols in rmarkdown  mac

### ISSUE THREAD

**Issue by rosingle** [rstudio/rmarkdown#1221]
Tks for you guy's efforts to make this language possible ! I have used phonetic symbols in rmarkdown and very sadly it doesn't work even under xelatex. It seems to me that  it's a font problem because when I set mainfont to Charis SIL the symbols appear.

So how could I use a specific font when I input phonetic symbols in rMarkdown ? Is it pratical if I have a lot of phonetic symbols everywhere in the doc ? An example is given here...

Mac High Sierra

````
---
title: "Report"
author: "try"
date: "12/13/2017"
output: 
  pdf_document:
   latex_engine: xelatex
---

# I want to mix several fonts (these with times new roman)

And now I study these vowels(always times new roman) [i a ɔ ɤ u y]  (these with Charis SIL)
````
