### ISSUE TITLE
TOC does not indent Level 3 Headings

### ISSUE THREAD

**Issue by carolynwclayton** [rstudio/rmarkdown#1235]
The table of contents in an HTML Rmarkdown document indents Level 2 headings correctly, but does not indent Level 3 headings further than Level 2 headings.

Here is the code used to generate the issue:
```
---
title: "Example"
output:
  html_document:
    toc: true
    toc_float:
      collapsed: false
    toc_depth: 3
---

# Title
## Section 1
### Section 1.1
## Section 2
```

Here is the resulting table of contents:
![screen shot 2018-01-04 at 3 17 48 pm](https://user-images.githubusercontent.com/10274351/34586826-e0823ade-f162-11e7-9526-9ee8d5432e4a.png)

Here is my session info:
![screen shot 2018-01-04 at 3 20 36 pm](https://user-images.githubusercontent.com/10274351/34586835-e690cec2-f162-11e7-8cc0-8d712f2ff4a2.png)
