### ISSUE TITLE
pdf_document not build correctly when template = NULL

### ISSUE THREAD

**Issue by NMarkgraf** [rstudio/rmarkdown#1295]
Hi folks,

when you produce a pdf_document with `template=NULL`, to use the native pandoc template instead of the rmarkdown templates, the output is not generated, because a document without a given template pandoc needs the "--standalone" parameter but this is missing.

```
---
title: "Minimal example not working"
author: "Norman Markgraf"
date: "21 März 2018"
output: 
    pdf_document:
        keep_tex: yes
        template: NULL
---

## R Markdown

This is an R Markdown document. Markdown is a simple formatting syntax for authoring HTML, PDF, and MS Word documents. For more details on using R Markdown see <http://rmarkdown.rstudio.com>.
```

```
---
title: "Minimal example working"
author: "Norman Markgraf"
date: "21 März 2018"
output: 
    pdf_document:
        keep_tex: yes
        template: NULL
        pandoc_args:
            - --standalone
---
## R Markdown

This is an R Markdown document. Markdown is a simple formatting syntax for authoring HTML, PDF, and MS Word documents. For more details on using R Markdown see <http://rmarkdown.rstudio.com>.

```
> rmarkdown::pandoc_version()
[1] ‘2.1.2’

> devtools::session_info('rmarkdown')
Session info -----------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.4.3 (2017-11-30)
 system   x86_64, darwin15.6.0        
 ui       RStudio (1.1.383)           
 language (EN)                        
 collate  de_DE.UTF-8                 
 tz       Europe/Berlin               
 date     2018-03-21                  

Packages ------------------------------------------------------------------------------------------
 package   * version date       source                        
 backports   1.1.2   2017-12-13 CRAN (R 3.4.3)                
 base64enc   0.1-3   2015-07-28 CRAN (R 3.4.0)                
 digest      0.6.15  2018-01-28 CRAN (R 3.4.3)                
 evaluate    0.10.1  2017-06-24 CRAN (R 3.4.1)                
 glue        1.2.0   2017-10-29 CRAN (R 3.4.2)                
 graphics  * 3.4.3   2017-12-07 local                         
 grDevices * 3.4.3   2017-12-07 local                         
 highr       0.6     2016-05-09 CRAN (R 3.4.0)                
 htmltools   0.3.6   2017-04-28 CRAN (R 3.4.0)                
 jsonlite    1.5     2017-06-01 cran (@1.5)                   
 knitr       1.20    2018-02-20 CRAN (R 3.4.3)                
 magrittr    1.5     2014-11-22 CRAN (R 3.4.0)                
 markdown    0.8     2017-04-20 CRAN (R 3.4.0)                
 methods   * 3.4.3   2017-12-07 local                         
 mime        0.5     2016-07-07 CRAN (R 3.4.0)                
 Rcpp        0.12.15 2018-01-20 CRAN (R 3.4.3)                
 rmarkdown   1.9.5   2018-03-21 local                         
 rprojroot   1.3-2   2018-01-03 CRAN (R 3.4.3)                
 stats     * 3.4.3   2017-12-07 local                         
 stringi     1.1.6   2017-11-17 CRAN (R 3.4.2)                
 stringr     1.3.0   2018-02-19 CRAN (R 3.4.3)                
 tinytex     0.4.1   2018-03-18 Github (yihui/tinytex@09383db)
 tools       3.4.3   2017-12-07 local                         
 utils     * 3.4.3   2017-12-07 local                         
 yaml        2.1.17  2018-02-27 cran (@2.1.17)
