### ISSUE TITLE
ToC in github_document: incorrect links for some special characters

### ISSUE THREAD

**Issue by misaugstad** [rstudio/rmarkdown#1319]
For the github_document output format only, the links in the ToC are broken when using some special characters. The period (`.`) character, for example. Here is an example Rmd doc:

````
---
title: "ToC Test"
output:
  github_document:
    toc: yes
---

# test1

# test2.
````

The link to test 1 works (`test_toc.md#test1`), but the link to test 2 does not (`test_toc.md#test2.`). If I replace the `.` with a `-`, it works (`test_toc.md#test2-`).

However, the `.` isn't always replaced by a '-'. If you use the header `test. test`, the correct link is `test_toc.md#test-test`.
