### ISSUE TITLE
Tabsets don't appear in ToC

### ISSUE THREAD

**Issue by Romain-B** [rstudio/rmarkdown#1336]
It appears that when headers are put in tabset format, they don't appear in the table of contents.
Even stranger : when there are subheaders inside the tabsets, these will appear in the toc, but there will be no separation or distinction between the subheaders of different tabs

````
---
title: Hello World
output: 
  html_document:
    toc: TRUE
    toc_float: true
    toc_depth: 4
---

# My header {.tabset}

## Tab 1
### subheader1
### subheader2

## Tab 2

### subheader1
### subheader2
````

![image](https://user-images.githubusercontent.com/18575069/39820568-6387b954-53a6-11e8-98e5-aca4f525495a.png)
