### ISSUE TITLE
Custom CSS and Logo with Shiny Presentation (ioslides)

### ISSUE THREAD

**Issue by mlduarte** [rstudio/rmarkdown#135]
Shiny presentation (ioslides) does not seem to allow for custom CSS, .e.g., 

``` yaml

---
title: "Habits"
author: John Doe
date: March 22, 2005
runtime: shiny
output:
  ioslides_presentation:
    css: temp.css

---
```

Please see http://stackoverflow.com/questions/24131827/shiny-presentation-ioslides-custom-css-and-logo?noredirect=1#comment37411961_24131827 for more details
