### ISSUE TITLE
MAC users: R markdown does not knit PDF beamer

### ISSUE THREAD

**Issue by ga122493** [rstudio/rmarkdown#1360]
Hello,

I am trying to knit pdf slides (pdf beamer) but R markdown does not work... However, regular pdf knitting and html slides knitting work fine. 

The first part of my code is 
```{r}
---
title: "xxx"
author: "xxx"
date: "`r Sys.Date()`"
output:
  beamer_presentation:
    includes:
      after_body: ~/Dropbox/Lecture 3/table-of-contents.txt
      in_header: ~/Dropbox/Lecture 3/Example-header-simple.txt
    slide_level: 3
  ioslides_presentation: default
  slidy_presentation: default
fontsize: 9pt
---
### Texts
xxxxx
```

Based on this post https://github.com/rstudio/rmarkdown/issues/1285, I tried
1.  downgrade to RMarkdown v1.8
```{r}
devtools::install_version("rmarkdown", version = "1.8", repos = "http://cran.us.r-project.org")
```
    then the error was 
```{r}
Error producing PDF.

Error: pandoc document conversion failed with error 43
Execution halted
```

2. install rmarkdown and tinytex from cran
```{r}
install.packages(c('rmarkdown', 'tinytex'))
```
    then the error was 
```{r}
Output created: Lecture3_slides-flight.pdf
Error in tools::file_path_as_absolute(output_file) : 
  file 'Lecture3_slides-flight.pdf' does not exist
Calls: <Anonymous> -> <Anonymous>
In addition: Warning message:
In file.rename(file_with_ext(texfile, "pdf"), output_file) :
  cannot rename file 'Lecture3_slides-flight.pdf' to 'Lecture3_slides-flight.pdf', reason 'No such file or directory'
Execution halted
```

Please help!!!!
Thank you very much

**Comment by NMarkgraf** [comment]
Please try the following:

1. Change your YAML to:

```
---
title: "xxx"
author: "xxx"
date: "`r Sys.Date()`"
output:
  beamer_presentation:
    includes:
      after_body: "~/Dropbox/Lecture 3/table-of-contents.txt"
      in_header: "~/Dropbox/Lecture 3/DOROS-beamer-header-simple.txt"
    slide_level: 3
  ioslides_presentation: default
  slidy_presentation: default
fontsize: 9pt
---
### Texts
xxxxx
```

2. If that won't fix it, please rename for diretory from "Lecture 3" to something without a space, like "Lecture_3" oder "Lecture3"

3. A good adwise at last:

NEVER USE A DROPBOX OR ANY OTHER CLOUD DIRECTORY FOR KNITR OR RMARKDOWN!


Latex don't like it! ;-)
