### ISSUE TITLE
pandoc2 and rmarkdown interaction for metropolis

### ISSUE THREAD

**Issue by eddelbuettel** [rstudio/rmarkdown#1393]
When using pandoc 2.2.1 (as shipped by RStudio, here linked to `~/bin/pandoc` as you see below) an otherwise fine RMarkdown presentation using the Metropolis theme fails with

```sh
/home/edd/bin/pandoc +RTS -K512m -RTS minex.utf8.md --to beamer \
   --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash \
   --output minex.tex --variable theme=metropolis --highlight-style tango \
   --pdf-engine xelatex --self-contained            
tlmgr search --file --global '/ucharcat.sty'        
Cannot determine type of tlpdb from /home/edd/texmf!            
cannot setup TLPDB in /home/edd/texmf at /usr/bin/tlmgr line 6071.             
! LaTeX Error: File `ucharcat.sty' not found.  
```

The file is of course present, and running with the older `pandoc` version 1.19.2.1 works fine (as shown below).

This happens with both the CRAN and the development versions of RMarkdown.

I used the following file `minex.Rm`:

````
---
author: Some Author
title: A Talk
subtitle: Subtitle
date: 1 Jan 2018
output:
  beamer_presentation:
    keep_tex: no
    theme: metropolis
    latex_engine: xelatex
classoption: compress
fontsize: 12pt
---

```{r, setup, include=FALSE}
knitr::opts_chunk$set(cache=TRUE)
```

# New Slide

## New Title

````

Once I remove the softlink, all is well:

```
edd@rob:~$ render.r minex.Rmd


processing file: minex.Rmd
  |......................                                           |  33%
  ordinary text without R code

  |...........................................                      |  67%
label: setup (with options) 
List of 1
 $ include: logi FALSE

  |.................................................................| 100%
  ordinary text without R code


output file: minex.knit.md

/usr/bin/pandoc +RTS -K512m -RTS minex.utf8.md --to beamer --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output minex.tex --variable theme=metropolis --highlight-style tango --latex-engine xelatex --self-contained 

Output created: minex.pdf
edd@rob:~$ 
```

As I would like to move to pandoc2 at some point, it would nice if this could be addressed. 

Could this be a preference for tinytex over a standard (working, complete, ...) texlive installation?

Ubuntu 17.10, R 3.4.4, everything from CRAN current
