### ISSUE TITLE
Darkly Theme Table Text Color

### ISSUE THREAD

**Issue by MBarrows20** [rstudio/rmarkdown#1413]
I'm so excited that Darkly is making its way into RMarkdown! However, after applying it to a document, I've noticed that the way tables are formatted makes it impossible to read every other row. Please see the image below. 

![image](https://user-images.githubusercontent.com/7907749/43076756-38f00eac-8e53-11e8-8a81-7a8b7b6e496f.png)

If you highlight the table, you can see that there is actually information in each of the white rows, they are just white text on a white background. 

![image](https://user-images.githubusercontent.com/7907749/43076859-9dc0281c-8e53-11e8-98c9-0e39f65e4a4b.png)

This document was created with the following yaml header: 

```
---
title: "Title"
author: "Name"
date: "Last Update: `r Sys.Date()`"
output: 
  html_notebook:
    highlight: pygments
    theme: darkly
    toc: yes
    toc_float: yes
---
```

and the table was constructed with the following code chunk:
```{r}
read.csv("../Data/ExampleCSV.csv")
```

I've installed both from the 282ece4 commit and from the master and both seem to produce the same table style. 

Please let me know if I can provide any more supporting documentation
