### ISSUE TITLE
logo: in yaml breaks flex_dashboard when using runtime: shiny

### ISSUE THREAD

**Issue by blitz2057** [rstudio/rmarkdown#1417]
Below is my yaml without logo: and I do have the yaml indented correctly. How can I fix this.

````
---
title: "Super Measures Dashboard"
output: 
   flexdashboard::flex_dashboard:
    theme: sandstone
    orientation: rows
    vertical_layout: fill
    source_code: embed
runtime: shiny
---
````
Below is the result:
![image](https://user-images.githubusercontent.com/40303139/43283980-68e95b08-90e8-11e8-9947-620e93c0c91f.png)

Now the yaml with the logo:

````
---
title: "Supermeasures Dashboard"
output: 
  flexdashboard::flex_dashboard:
    logo: logo.png
    theme: sandstone
    orientation: rows
    vertical_layout: fill
    source_code: embed
runtime: shiny
---
````
Below is the result:
![image](https://user-images.githubusercontent.com/40303139/43284764-d5933132-90ea-11e8-828e-04b9247f77ac.png)
