### ISSUE TITLE
Differential treatment of fonts for xelatex and lualatex : can't set mathfont in lualatex.

### ISSUE THREAD

**Issue by EmmanuelCharpentier** [rstudio/rmarkdown#1421]
Setup : rmarkdown (development version, as recommended) running on R 3.5.1.
```
> sessionInfo()
R version 3.5.1 (2018-07-02)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux buster/sid

Matrix products: default
BLAS: /usr/lib/x86_64-linux-gnu/openblas/libblas.so.3
LAPACK: /usr/lib/x86_64-linux-gnu/libopenblasp-r0.3.2.so

locale:
 [1] LC_CTYPE=fr_FR.utf8       LC_NUMERIC=C             
 [3] LC_TIME=fr_FR.utf8        LC_COLLATE=fr_FR.utf8    
 [5] LC_MONETARY=fr_FR.utf8    LC_MESSAGES=fr_FR.utf8   
 [7] LC_PAPER=fr_FR.utf8       LC_NAME=C                
 [9] LC_ADDRESS=C              LC_TELEPHONE=C           
[11] LC_MEASUREMENT=fr_FR.utf8 LC_IDENTIFICATION=C      

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] compiler_3.5.1    magrittr_1.5      htmltools_0.3.6   tools_3.5.1      
 [5] yaml_2.2.0        tinytex_0.6       Rcpp_0.12.18      stringi_1.2.4    
 [9] rmarkdown_1.10.10 highr_0.7         knitr_1.20        htmldeps_0.1.1   
[13] xfun_0.3          digest_0.6.15     stringr_1.3.1     evaluate_0.11    
```

YAML header : 
```
---
title: Notes sur l'analyse préliminaire d'EVACFAOD
author: Emmanuel Charpentier
date: Juillet 2018
lang: fr-FR
mainfont: TeX Gyre Termes
sansfont: TeX Gyre Heros
monofont: Inconsolata
mathfont: TeX Gyre Termes Math
documentclass: article
classoption: a4paper,twoside
output:
  pdf_document:
    toc: true
    number_sections: true
    keep_tex: true
    latex_engine: lualatex
---
```

(Top of the) resulting \LaTeX file : 
```
\documentclass[french,a4paper,twoside]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
\else % if luatex or xelatex
  \ifxetex
    \usepackage{mathspec}
  \else
    \usepackage{fontspec}
  \fi
  \defaultfontfeatures{Ligatures=TeX,Scale=MatchLowercase}
    \setmainfont[]{TeX Gyre Termes}
    \setsansfont[]{TeX Gyre Heros}
    \setmonofont[Mapping=tex-ansi]{Inconsolata}
    \setmathfont(Digits,Latin,Greek)[]{TeX Gyre Termes Math}
\fi
```

Error message in the `.log` file : 

```
! Undefined control sequence.
<recently read> \setmathfont 
             
l.19     \setmathfont
                   (Digits,Latin,Greek)[]{TeX Gyre Termes Math}
```

When `lualatex` is replaced by `xelatex`, the file compiles fine.

I note that, when using `xelatex`, the `mathspec` package gets loaded (which supposedly `require`s `fontspec`), whereas when using `lualatex`, only `fontspec` is loaded. Why is `luatex` treated differently from `xetex` ? Hence two questions : 

1) Why not load `mathspec` when using `lualatex` ?, or, alternatively

2) Why not load *both* `fontspec` *and* `unicode-math` in both cases ?

I also tried to directly redefine the mono font from LaTeX, with no success.

A couple of bonus questions (see this Stackoverflow [question](https://stackoverflow.com/questions/51693042/how-to-pass-options-to-a-font-in-rmarkdown)). 

1) Where does the `Mapping=tex-ansi` option to `setmonofont` comes from, and why ?

2) How to pass options to fonts ?
