### ISSUE TITLE
\end{enumerate}} \\ - issue ?

### ISSUE THREAD

**Issue by aleksandar-spasojevic** [rstudio/rmarkdown#145]
Hi there,

I'm trying to render this solutions.Rmd file:

```

---
title: "Solutions"
author: "Aleksandar Spasojevic"
date: "27. Juni 2014"
output:
  pdf_document:
    fig_crop: no
    keep_tex: yes
    number_sections: yes
    toc: yes

---

Test
```

`render("solutions.Rmd", "pdf_document")` produces:

```
! LaTeX Error: There's no line here to end.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              

l.67 \end{enumerate}} \\

pandoc: Error producing PDF from TeX source
Error: pandoc document conversion failed with error 43
```

A look into solutions.tex File solved the issue by deleting the `\\` on line 67. 

```
...
\begin{document}

\begin{center}
\huge Solutions \\[0.2cm]
\large \emph{Aleksandar Spasojevic}\\[0.1cm]
\large \emph{\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{26}
\itemsep1pt\parskip0pt\parsep0pt
\item
  Juni 2014
\end{enumerate}} \\ % '\\' has to be removed for compiling
\normalsize
\end{center}
...
```

Is this an issue caused by rmarkdown or is my latex installation just stupid to neglect this newline 'operator' (excuse me for, somehow, latex questions)?

Cheers
Aleksandar
