### ISSUE TITLE
Rendering of own html template fails after update to rmarkdown version 1.10

### ISSUE THREAD

**Issue by Kangaroo76** [rstudio/rmarkdown#1452]
I'm on windows using R version 3.5.1.

After updating rmarkdown from version 1.9 to version 1.10 rendering fails when using an own template.

I was not able to fix this but going back to version 1.9 solved the issue again.

Rendering with
````
---
title: My report
output: 
  html_document:
    self_contained: yes
    number_sections: true
---
````

is working but rendering with own template fails

````
---
title: My report
output: 
  CSStemplate::html_report2:
    self_contained: yes
    number_sections: true
---
````

The error is actually generated by pandoc

````
pandoc.exe: theme:bootstrap: openBinaryFile: does not exist (No such file or directory)
````

I could not figure out why it works in 1.9 but not in 1.10 so far. I already tried updating pandoc and going to the latest version of rmarkdown from github but it did not solve the problem.

Please let me know if more details are necessary.
