### ISSUE TITLE
Can produce .tex file, but get "Undefined control sequence." Error

### ISSUE THREAD

**Issue by MCM-Math** [rstudio/rmarkdown#1523]
I've looked at other "Undefined control sequence" pages, but mine seems to be a different case:

Running R Markdown produces a .tex file, but I get the following error: 

! Undefined control sequence.
l.41 \DeclareRelease
                           {v1}{2001-04-09}{parskip-2001-04-09.sty}

The pandoc command uses default-1.17.0.2.tex as the template.  The .tex file can be compiled by TeXworks just fine, and the document seems to come out fine, so I don't know where the breakdown is occurring.

**Comment by yihui** [comment]
It would be hard to tell without a minimal reprex.

**Comment by MCM-Math** [comment]
`---
documentclass: article
output:
  bookdown::pdf_document2:
    keep_tex: true
    fig_caption: true
    number_sections: true
    toc: no
header-includes:
- \usepackage{setspace}
- \usepackage{fancyhdr}
- \usepackage{lipsum}
- \usepackage{float}
- \usepackage[numbered]{bookmark}
- \floatstyle{plaintop}
- \restylefloat{figure}
- \floatplacement{figure}{H}
- \pagestyle{fancy}
---
`

**Comment by MCM-Math** [comment]
```
---
documentclass: article
output:
  bookdown::pdf_document2:
    keep_tex: true
    fig_caption: true
    number_sections: true
    toc: no
header-includes:
- \usepackage{setspace}
- \usepackage{fancyhdr}
- \usepackage{lipsum}
- \usepackage{float}
- \usepackage[numbered]{bookmark}
- \floatstyle{plaintop}
- \restylefloat{figure}
- \floatplacement{figure}{H}
- \pagestyle{fancy}
---
```
