### ISSUE TITLE
ioslides: mathjax = local doesn't work on Windows

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rmarkdown#153]
```

---
title: "Test"
author: "DM"
output:
  ioslides_presentation:
    mathjax: local
    self_contained: false

---
## R Markdown

$$a=b$$
```

Appears to be due to mismatched backslashes:

`script.src = "a_files\mathjax-2.3.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML";`

Originally reported at http://rmarkdown.rstudio.com/ioslides_presentation_format.html#comment-1473993760.
