### ISSUE TITLE
Enabling toc_float strips the text format

### ISSUE THREAD

**Issue by codetrainee** [rstudio/rmarkdown#1548]
Enabling `toc_float` strips the text format such as *italic*, **blod** or superscript. 
```
---
output:
  html_document:
    toc: yes
    toc_float: yes
    toc_depth: 3
---

## test *italic*

## test **bold**

## test 10^6^
```
![image](https://user-images.githubusercontent.com/8357863/54356933-eb74ce80-46b0-11e9-9cbc-7e25bc0e1c4d.png)
