### ISSUE TITLE
Embedded default CSS in HTML output causes wrong color when printing

### ISSUE THREAD

**Issue by wiedenhoeft** [rstudio/rmarkdown#1616]
I am including a css file into my Rmd which changes the color of section headers to blue.

test.Rmd
```Rmd
---
title: This is a test file
author: John Doe
output:
 html_document:
  css: style.css
--- 


# Test title #

Lorem ipsum and so forth.

# Session Info #

```{r, include = TRUE}
sessionInfo ()
` ` ` 
```

style.css:

```css
body {
	hyphens: auto;
	text-align: justify
}

h1, .h1 {
	margin-top: 100px;
} 

h2, .h2 {
	margin-top: 80px;
} 

h3, .h3 {
	margin-top: 60px;
} 

h4, .h4 {
	margin-top: 40px;
} 

h1, h2, h3, h4, h5, h6 {
	font-weight:bold;
	color: #0072B2;
}

table {
	margin-top: 50px;
	margin-bottom: 50px;
}


img {
	page-break-before: auto; 
	page-break-after: auto; 
	page-break-inside: avoid; 
	margin-top: 50px;
	margin-bottom: 50px;
}

h4.author{
	margin-top: 30px;
	margin-bottom: 30px;
}


@page {  
	margin-left: 2cm;  
	margin-right: 2cm;  
	margin-top: 2cm;  
	margin-bottom: 2cm;  
}
```
The HTML document renders as expected, with the section headers in blue. However, when I print the HTML file, all section headers are black. This is because RStudio embeds a large CSS file in the HTML (line 20). The problem is caused by the following part:

```css
@media print {
	*, :after, :before {
	color:#000!important;
	text-shadow:none!important;
	background:0 0!important;
	-webkit-box-shadow:none!important;
	box-shadow:none!important;
}
```
specifically the color attribute. If I remove this via

```bash
cat test.html | sed 's/color%3A%23000%21important%3B//g' > test_fixed.html
```

the file prints as expected.

**Comment by RLesur** [comment]
The CSS rule pointed in this issue comes from the [Bootstrap](https://bootstrapdocs.com/v3.3.5/docs/) library.
It [was introduced](https://github.com/twbs/bootstrap/commit/a8b9342aea29632928cac4c3458faf80c682d9d1) in Bootstrap 2.2.2 and removed in Bootstrap 4.0.0 (see the [related issue](https://github.com/twbs/bootstrap/issues/14031) in the Bootstrap project).


@wiedenhoeft As described in [_R Markdown: the Definitive Guide_](https://bookdown.org/yihui/rmarkdown/html-document.html#appearance-and-style) when you use the default value for the `theme` variable, you choose to use a Bootstrap theme (you can remove Bootstrap with `theme: null`, see [here](https://bookdown.org/yihui/rmarkdown/html-document.html#custom-css)). 
More precisely, **rmarkdown** HTML documents use Bootstrap 3.3.5.

A strategy could be to insert in your `style.css` file a CSS rule with a higher [specificity](https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity) to override the Bootstrap's one, for example:

```css
@media print {
  h1, h2, h3, h4, h5, h6 {
    color: #0072B2 !important;
  }
}
```
