### ISSUE TITLE
html_vignette, if self_contained = false, document_files/  deletes unless keep_md = yes

### ISSUE THREAD

**Issue by mstr3336** [rstudio/rmarkdown#1639]
---

By filing an issue to this repo, I promise that

- [x] I have fully read the issue guide at https://yihui.name/issue/.
- [x] I have provided the necessary information about my issue.
    - If I'm asking a question, I have already asked it on Stack Overflow or RStudio Community, waited for at least 24 hours, and included a link to my question there.
    - If I'm filing a bug report, I have included a minimal, self-contained, and reproducible example, and have also included `xfun::session_info('rmarkdown')`. I have upgraded all my packages to their latest versions (e.g., R, RStudio, and R packages), and also tried the development version: `remotes::install_github('rstudio/rmarkdown')`.
    - If I have posted the same issue elsewhere, I have also mentioned it in this issue.
- [x] I have learned the Github Markdown syntax, and formatted my issue correctly.

I understand that my issue may be closed if I don't fulfill my promises.

# Problem description

By default, `rmarkdown::html_vignette` sets `keep_md = FALSE`, however, this default causes unexpected behaviour when attempting to set `self_contained = FALSE` , as rmarkdown appears to delete the resources folder as well when keep_md is set to FALSE.

I'm not really sure this behaviour makes sense / whether `keep_md = FALSE` should interact with `self_contained = FALSE` in this way. 

I wonder if this should be documented, or if these combination of params should raise a warning, or if `keep_md = FALSE` should be more "polite" to `self_contained = FALSE` ?

# Session Info

```
R version 3.5.2 (2018-12-20)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Mojave 10.14.6, RStudio 1.1.463

Locale: en_AU.UTF-8 / en_AU.UTF-8 / en_AU.UTF-8 / C / en_AU.UTF-8 / en_AU.UTF-8

Package version:
  base64enc_0.1.3 digest_0.6.18   evaluate_0.14   glue_1.3.0      graphics_3.5.2  grDevices_3.5.2 highr_0.7       htmltools_0.3.6 jsonlite_1.6   
  knitr_1.22      magrittr_1.5    markdown_1.1.1  methods_3.5.2   mime_0.6        Rcpp_1.0.0      rmarkdown_1.15  stats_3.5.2     stringi_1.3.1  
  stringr_1.4.0   tinytex_0.15    tools_3.5.2     utils_3.5.2     xfun_0.9        yaml_2.2.0     

Pandoc version: 1.19.2.1
```

# keep_md unset

## Front matter

```yaml
---
title: "Untitled"
author: "Matthew Strasiotto"
date: "04/09/2019"
output: 
  rmarkdown::html_vignette:
    self_contained: no
    #keep_md: yes
vignette: >
  %\VignetteIndexEntry{Untitled}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
```

## Rmd document

```{r pressure, echo=FALSE}
plot(pressure)
```
# Keep_md set

```yaml
---
title: "Untitled"
author: "Matthew Strasiotto"
date: "04/09/2019"
output: 
  rmarkdown::html_vignette:
    self_contained: no
    keep_md: yes
vignette: >
  %\VignetteIndexEntry{Untitled}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
```

```{r pressure, echo=FALSE}
plot(pressure)
```
