### ISSUE TITLE
Unable to select nothing value for select param with multiple and initial value

### ISSUE THREAD

**Issue by gadenbuie** [rstudio/rmarkdown#1674]
In a parameterized document, when the parameter input type is `select` and `multiple: true` is enabled **and** an initial value is set, it's not possible to select a null (or nothing/empty) option.

Here's a small reprex that creates two options. Launch _Knit with parameters_ and deselect `a` and `b` in the first option. When knitting the document, `params$mult_with_initial` will be `c("a", "b")` rather than the expected `""`.

````
---
title: "Null Selection Issue"
output: html_document
params:
  mult_with_initial:
    label: Choose Multiple or None (starts selected, deselect options)
    value: ["a", "b"]
    input: select
    multiple: true
    choices: !r c("No selection" = "", letters[1:2])
  mult_start_empty:
    label: Choose Multiple or None (starts empty)
    value: ""
    input: select
    multiple: true
    choices: !r c("No selection" = "", letters[1:2])
---

Deselect `a` and `b` in the first option, 
but note that they are added back as the default selection.

```{r}
str(params)
```

Expected behavior

```{r}
str(list(mult_with_initial = "", mult_start_empty = ""))
```
````

After removing `a` and `b` from the selection...

![image](https://user-images.githubusercontent.com/5420529/67107877-4b79a900-f19b-11e9-8744-201339fcb6b2.png)

...the resulting document shows:

![image](https://user-images.githubusercontent.com/5420529/67107981-7e23a180-f19b-11e9-8002-32c3319dae40.png)

**Comment by cderv** [comment]
A bit of context an explanation about this issues. 

There is a special handling in the shiny app for params selection
https://github.com/rstudio/rmarkdown/blob/0af6b3556adf6e393b2da23c66c695724ea7bd2d/R/params.R#L413-L424
This means that when the input return NULL or same as the default, it will not be in the return value list `values`

`values` is what is returned by the app
https://github.com/rstudio/rmarkdown/blob/0af6b3556adf6e393b2da23c66c695724ea7bd2d/R/params.R#L434
https://github.com/rstudio/rmarkdown/blob/0af6b3556adf6e393b2da23c66c695724ea7bd2d/R/params.R#L15-L17

and we'll be merged with initial params from yaml
https://github.com/rstudio/rmarkdown/blob/0af6b3556adf6e393b2da23c66c695724ea7bd2d/R/params.R#L37

So as input is empty, the `mult_with_initial` will not be part of `value` and so when list are merged the default value will be set in `params` which is what is return in the example above. 

I believe this is also like that because `selectInput()` does not return empty string among the choices `""` but returns NULL as nothing is selected. 

Small shiny apps 
````r
library(shiny)
shinyApp(
  ui = fluidPage(
    selectInput("choice", "Choose Multiple or None (starts selected, deselect options)",
                c(letters[1:2], "No selection" = ""), 
                selected = c("a", "b"), 
                multiple = TRUE 
    ),
    verbatimTextOutput("result")
  ),
  server = function(input, output) {
    output$result <- renderText({
      capture.output(str(input$choice))
    })
  }
)
````

If I deselect the initial values, I don't get an empty character but I get NULL as a return value from `selectInput`
![image](https://user-images.githubusercontent.com/6791940/148933172-4765e41a-aade-4dd0-b96d-e31a217006cf.png)

It seems like the expected behavior from the doc
> In selectize mode, if the first element in choices has a value of "", its name will be treated as a placeholder prompt. For example: selectInput("letter", "Letter", c("Choose one" = "", LETTERS))

You would have to use `selectize = FALSE` in this case to make it works. Try with that: 

```` yaml
params:
  mult_with_initial:
    label: Choose Multiple or None (starts selected, deselect options)
    value: ["a", "b"]
    input: select
    multiple: true
    choices: !r c("No selection" = "", letters[1:2])
    selectize: false
````

Selecting no selection will return in the Rmd what you expect. 

So I don't think there is any issue here. 

What your thoughts based on this little investigation ? 

Thanks
