### ISSUE TITLE
include footer.html causes this error pandoc: end.html: openBinaryFile: does not exist

### ISSUE THREAD

**Issue by abiyug** [rstudio/rmarkdown#1680]
I am trying to add a footer to a rmakrdown website by adding `include:after_body: foobar.html`  in the _site.yml file. When I knit with the "build website" button, I get the "pandoc: end.html" file doesn't exist error.   

Initially I thought it had to do with pandoc, but after fiddling a bit,  it turns out to NOT be a pandoc issue, that is what I think anyway.  Here is how I am able to reproduce it.

```
> packageVersion("rmarkdown")
[1] ‘1.16.2’

```
The setup and steps I have taken to replicate the problem and work around:
1/ flat directory
2/ files in the directory: index.Rmd, About.Rmd, footer.Rmd
3/ my _site.yaml looks like this
```
output:
  html_document:
     theme: cerulean
     highlight: textmate
     include:
       after_body: footer.hml
     css: styles.css/ 

```
4/ When I press the knit button - index.html, About.html and footer.html get copied to "_site" directory. And the first go around works fine. 
5/ Next, I edited the footer.Rmd and when press the knit button I get "pandoc openBinaryFile doesn't exist error".
5/ To work around that. a) I remove the include after_body from the yml, and save. b) Delete the footer.hml from **_site** directory, c) knit the footer.Rmd file on its own (which copies the foother.html to _site directory. d) I then manually move the footer.html back to the home directory (where the footer.Rmd is), and e) re-add the include after_body again back to _site.yml, and knit. This website rendered without pondoc issue after that. 

I didn't experience the same issue for the index and about Rmd files. I can make changes and any time and they copy the respective .html to _site with changes made, and when knit they render with no manual add/delete or messing with the _site.yml.  

The footer.Rmd and _site are misbehaving somehow. It seems to me , somewhere in the script that looks at the yaml and the _site directory to render with pandoc is not quite right.

**Comment by abiyug** [comment]
To replicate the problem you have to knit **twice**:
1/ The first knit should show the footer on every page.
2/ make a change in the footer.Rmd and knit again. This will reproduce the error.

Here is the _site.yml config.
```
title: "test"
name: "my-website"
navbar:
  title: "dataRecode.com"
  type: inverse
  right:
    - text: "Home"
      icon: fa-home
      href: index.html
    - text: "About"
      icon: fa-gear
      href: about.html
output:
  html_document:
     theme: cerulean
     highlight: textmate
     includes:
       after_body: footer.html 
     css: styles.css
```

**Comment by abiyug** [comment]
I think this is a bug. Can someone take a look?

**Comment by cderv** [comment]
Can you share a reproductible example as a whole project ? this would help understand what you are trying to achieve. 

I don't think this is a really a bug. From what I understand, you are trying to use one of the knitted Rmd file as footers for the others. However, you applied the same `output` that includes the footer for all the documents included the `footer.Rmd`. 
I think Rmarkdown website generator processes each Rmd file one after the other alphabetically. When `About.Rmd` is rendered, `footer.html` does not exists yet, so you get the error. Even if it was rendered first, it would be in the `_site` directory with the other html, and not at the root of the project where to told pandoc to look for it (`after_body: footer.html ` not `after_body: _site/footer.html `. 

If you want to add a footer to all the document, I am not sure this is the way to go. The easiest way is to create your `footer.html` file independently from other files. A `_footer.Rmd` that you would knit manually would not be picked up by site generator as a common Rmd file for your site. 
Among other solutions, you could use a custom generator that process `footer.Rmd` first by itself in a `html_fragment` then use the generated file as footers for others. 
You could also use the knitr `cat` engine to create the `footer.html` file in the first rendered file so that it exists. 

Anyway, I don't think what you want to do is standard and cover by default as you think it is or should. I am not sure though - a real reproductible example of what you want to do could really help. 

Thanks.

> as reference, see the documentation about [Rmarkdown Website](https://bookdown.org/yihui/rmarkdown/rmarkdown-site.html#common-elements)

**Comment by abiyug** [comment]
@cderv first thanks for getting back. Ok, you can run the following command to 

The objective is to have a footer gets appended after every page. And be able to modify footer.Rmd and re-run site build.

you can rerproduce with the following commands from CLI.

Step 1/ create the files
```
$ mkdir testWeb
$ touch About.Rmd index.Rmd footer.Rmd _site.yml
$ echo 'About Content' >> About.Rmd
$ echo 'Home Content' >> index.Rmd
$ echo 'footer Content 1' >> footer.Rmd
```

Step 2: Add content in the _site.yml
```
me: "my-website"
navbar:
  title: "My Website"
  left:
    - text: "Home"
      href: index.html
    - text: "About"
      href: about.html
  output:
    html_document:
      theme: cosmo
      highlight: textmate
      include:
        after_body: footer.html
```
Step 3:

From R CLI
`rmarkdown::render_site()`

After the first render site, if you change the footer.Rmd and re-run render_site, you will get the error.

**Comment by abiyug** [comment]
?

**Comment by cderv** [comment]
> 
> 
> ?

Pinging an issue like that is not necessary. It has only been 10 days since last message and it won't help give you an answer. Also, can you please ping more nicely that just one single character ? 

I did not had time to look into this more yet but I am still believing there is no bug.

Rmarkdown website will render every rmd file in order except Rmd doc recognized as [partials](https://bookdown.org/yihui/rmarkdown/rmarkdown-site.html#crmd-partials). Also it will apply output format to all document, including `footer.Rmd` in your case trying to include `footer.html` in `footer.Rmd` seems very strange...
 
I already gave you some hints toward solutions. Did you try any other workflow from the ideas in https://github.com/rstudio/rmarkdown/issues/1680#issuecomment-550037767 ?

**Comment by abiyug** [comment]
Didn't mean to frustrate you with a "?". Point taken.

If you run the "reproducible" code I provided, you can replicate the problem. Did you get a chance to test that? Thanks.

**Comment by cderv** [comment]
Yes I did try you example 

```sh
$ mkdir testWeb
$ cd testWeb
$ touch About.Rmd index.Rmd footer.Rmd _site.yml
$ echo 'About Content' >> About.Rmd
$ echo 'Home Content' >> index.Rmd
$ echo 'footer Content 1' >> footer.Rmd
```

For `_site.yml` your example is wrong I think 
* first line is truncated `me: "my-website"` should be `name: "my-website"` 
* `include:` should be `includes` 
* `about.html` should be `About.html` otherwise the link in menu does not work. 

With those corrections, I put this in `_site.yml`
```
name: "my-website"
navbar:
  title: "My Website"
  left:
    - text: "Home"
      href: index.html
    - text: "About"
      href: about.html
  output:
    html_document:
      theme: cosmo
      highlight: textmate
      includes:
        after_body: footer.html
```

After that I ran `Rscript -e 'rmarkdown::render_site()'` then `Rscript -e 'servr::httd("_site")'` to serve the website.

I get no error and a working site but no footer. If I modify the footer.Rmd and re-rendered I got no error. 

This example does not seem to reproduce any error and I don't see any footer. 
It seems I am missing something...

**Comment by abiyug** [comment]
You are right, as mentioned above, the example doesn't produce footer on all pages. That is the problem.

To show the footer on all pages, move the footer.Rmd outside of the current directory, knit separately and manually copy the rendered footer.html to the testWeb directory. After that when you build the website, the footer shows on all pages. HOWEVER, thought you see the footer on all pages now, it creates another problem. It disable "table of content" on pages.  I suppose there might be style conflict when you bring in the footer.html that was rendered outside. 

Section [3.1.1.1](https://bookdown.org/yihui/rmarkdown/html-document.html) here states to simply add footer.html in the _site.yaml, doesn't specify if the footer.Rmd should also exist in the home directory.

If you remove the **includes after_body footer** from yaml, the toc shows up again.  You can add a simple toc on the index to see the effect

---
output: 
  html_document:
    toc: true
---

**Comment by abiyug** [comment]
Setting the theme in the foother.Rmd to "null" fixed the "toc" issue! Setting the same theme for the footer.Rmd as the rest of the website didn't work.

In case someone else run into the same issue:
1/ The footer.Rmd should not seat in the home directory ( initially I had it in the home directory)
2/ If specific theme is used  for rmarkdown website (ex. united),  set the theme for the footer.Rmd to "null" which will void it of any default style set. <this worked for what I needed to do, but not sure if this is THE fix> 

Thanks to @cderv for the help.

**Comment by cderv** [comment]
Glad you find a workflow that suits you. I just want to share how I would do what you want. I add a misdirection in my previous test because you `_site.yml` example did not have a correct indentation and your `output` fields where not taken into account. I want to illustrate what I adviced above with _partials_. 

```sh
$ mkdir testWeb
$ cd testWeb
$ touch About.Rmd index.Rmd footer.Rmd _site.yml
$ echo 'About Content' >> About.Rmd
$ echo 'Home Content' >> index.Rmd
# create a partials, a Rmd beginning with _ so that it is not taken into account by render_site
$ echo 'footer Content 1' >> footer.Rmd
```
Create a `_site.yml` with this content (indentation is important). Note the footer name `_footer.html`
```yaml
name: "my-website"
navbar:
  title: "My Website"
  left:
    - text: "Home"
      href: index.html
    - text: "About"
      href: About.html
output:
  html_document:
    theme: cosmo
    highlight: textmate
    includes:
      after_body: _footer.html
```

Then render the footer as a `html_fragment` 
```r
Rscript -e 'rmarkdown::render("_footer.Rmd", output_format = "html_fragment")'
```
It will be rendered as `_footer.html` and place in the root folder.

Render the website (_footer.Rmd will be ignored)
```r
Rscript -e 'rmarkdown::render_site()'
```

Serve the website
```r
Rscript -e 'servr::httd("_site")'
```

If you need to modify the footer, you just have to change the Rmd and re render the partials. 
You can create a makefile to organise the step. 

How do you find this workflow ? I think it should be done that way. 

Hope it helps.
