### ISSUE TITLE
find_external_resources does not locate Office templates

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rmarkdown#1696]
## Repro

Save this doc as example.Rmd:

```
---
title: "Templates"
output:
  powerpoint_presentation:
    reference_doc: template.potx
---

### Overview
```

(if you don't have a `potx` file, just make an empty one)

Next, run `find_external_resources`:

```
> rmarkdown::find_external_resources("~/scratch/example.Rmd")
[1] path     explicit web     
<0 rows> (or 0-length row.names)
```

The external resource is not discovered.

This is where this usually happens:

https://github.com/rstudio/rmarkdown/blob/7ad693e10a7444de60e4f58bc3eef14eab212d35/R/html_resources.R#L285-L299
