### ISSUE TITLE
Icon hyperlinks no longer visible in R markdown using YAML html_document

### ISSUE THREAD

**Issue by a-brasch** [rstudio/rmarkdown#1924]
I previously had success adding headers and footers to my R markdown HTML files using guidance found here: [Pimp my RMD](https://holtzy.github.io/Pimp-my-rmd/#footer_and_header). No changes have been made to my header.html, but now the icon hyperlinks are no longer visible when knit via RStudio. I confirmed that the URL is still valid. The hyperlink via "Author Name" is still visible. When the header.html file is opened in Chrome, the hyperlink icons are visible and valid. Why would the hyperlink icons no longer be visible in the markdown HTML?

I posted this same question on [stackoverflow ](https://stackoverflow.com/questions/64309378/icon-hyperlinks-no-longer-visible-in-r-markdown-using-yaml-html-document-includ)and the [R Community](https://community.rstudio.com/t/icon-hyperlinks-no-longer-visible-in-r-markdown-using-yaml-html-document/84317), but no answers to-date.

Examples included below and a zip file containing an .rmd, header.html, footer.html, and knit html file is attached. As you can see from [this link](https://a-brasch.github.io/PSU-USP522-Practicum/), the icons and hyperlinks used to be visible.
[html_header_icons_issue.zip](https://github.com/rstudio/rmarkdown/files/5382230/html_header_icons_issue.zip)

Thanks for any insight,
Alex

My YAML looks like this:
```
---
title: "html_header_icons_issue"
author: "a-brasch"
date: "10/14/2020"
output:
  html_document:
    includes:
      before_body: ./header.html
      after_body: ./footer.html
---
```

My header.html file looks like this:
```
<p style="text-align: right;"><a href="mailto:SomeEmailAddress@gmail.com">Author Name</a></p>
<!-- Add icon library -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css">
<!-- Add font awesome icons -->
<p style="text-align: right;">
    <a href="https://stackoverflow.com/questions/64309378/icon-hyperlinks-no-longer-visible-in-r-markdown-using-yaml-html-document-includ" class="fas fa-chart-bar"></a>
    <a href="https://community.rstudio.com/t/icon-hyperlinks-no-longer-visible-in-r-markdown-using-yaml-html-document/84317" class="fab fa-linkedin"></a>
    <a href="https://yihui.org/issue/" class="fab fa-github"></a>
</p>
```

---

By filing an issue to this repo, I promise that

- [x] I have fully read the issue guide at https://yihui.org/issue/
- [x] I have provided the necessary information about my issue.
    - If I'm asking a question, I have already asked it on Stack Overflow or RStudio Community, waited for at least 24 hours, and included a link to my question there.
    - If I'm filing a bug report, I have included a minimal, self-contained, and reproducible example, and have also included `xfun::session_info('rmarkdown')`. I have upgraded all my packages to their latest versions (e.g., R, RStudio, and R packages), and also tried the development version: `remotes::install_github('rstudio/rmarkdown')`.
    - If I have posted the same issue elsewhere, I have also mentioned it in this issue.
- [x] I have learned the Github Markdown syntax, and formatted my issue correctly.

I understand that my issue may be closed if I don't fulfill my promises.

**Comment by cderv** [comment]
I don't really know why it worked before but it seems this is a Pandoc related issue when producing self_contained document. 

in self contained mode, this will be transformed to be integrated in the html file source code
```html
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css">
```
and it seems that does not play well with fontawesome. 

You can set `self_contained = FALSE` and it should work. 

If you are not bound to version 5.15.1 you used above, you can also use the fontawesome dependency included with rmarkdown bu using this in your document.
````md
```{r setup, include=FALSE}
htmltools::tagList(rmarkdown::html_dependency_font_awesome())
```
```
The version is 5.1.0 I think. 

And It seems to work. 

Also which version of Pandoc are you using ? `rmarkdown::pandoc_version()` ?

**Comment by cderv** [comment]
> self_contained: = FALSE threw this error: "Error in if (self_contained) { : argument is not interpretable as logical
Calls: ... do.call -> -> output_format -> html_document_base
Execution halted"

This should be 
```yaml
self_contained: FALSE
```
if you use it the yaml header under `html_document`

> I did not have to update my header/footer.html files, but to remove redundancy or potential confusion, I removed the following:

Yes I forgot to mention that. Good to know that it works correctly with this.

**Comment by a-brasch** [comment]
Of course, thanks for the correction.

**Comment by a-brasch** [comment]
As mentioned on Oct. 15, 2020, using the following worked, but 8 days later, after nothing has changed in the rmd file, the icons are once again missing. Any suggestions?

YAML
```
---
title: "html_header_icons_issue"
author: "a-brasch"
date: "10/14/2020"
output:
  html_document:
    includes:
      before_body: ./header.html
      after_body: ./footer.html
---
```

in combination with 

```
{r setup}
# Use font awesome to display icons within header and footer html files
htmltools::tagList(rmarkdown::html_dependency_font_awesome())
```

**Comment by a-brasch** [comment]
As mentioned on Oct. 15, 2020, using the following worked, but 8 days later, after nothing has changed in the rmd file, the icons are once again missing. Any suggestions?

YAML
```
---
title: "html_header_icons_issue"
author: "a-brasch"
date: "10/14/2020"
output:
  html_document:
    includes:
      before_body: ./header.html
      after_body: ./footer.html
---
```

in combination with 

```
{r setup}
# Use font awesome to display icons within header and footer html files
htmltools::tagList(rmarkdown::html_dependency_font_awesome())
```

**Comment by a-brasch** [comment]
As mentioned on Oct. 15, 2020, using the following worked, but 8 days later, after nothing has changed in the rmd file, the icons are once again missing. Any suggestions?

YAML
```
---
title: "html_header_icons_issue"
author: "a-brasch"
date: "10/14/2020"
output:
  html_document:
    includes:
      before_body: ./header.html
      after_body: ./footer.html
---
```

in combination with 

```
{r setup}
# Use font awesome to display icons within header and footer html files
htmltools::tagList(rmarkdown::html_dependency_font_awesome())
```

**Comment by ckelly17** [comment]
Did you ever get a fix on this? Having the same issue. Didn't change code bu fa-icons are now missing from knitted files.

**Comment by a-brasch** [comment]
Unfortunately, no. That's why I reopened the issue, but it hasn't gotten any traction.

**Comment by jsaraviadrago** [comment]
Hi! 

I have the exact same problem, I've being going around the internet for ours now. My .yaml file looks something like this. 

----
```

name: "Juan Carlos Saravia"
output_dir: "."
navbar:
  title: "Juan Carlos Saravia"
  left:
    - text: "Portafolio"
      href: portafolio.html
    - text: "Consulting"
      href: research.html
    - text: "Programming"
      href: software.html
    - text: "Data Science for good"
      href: blogs.html
  right:
    - icon: fa-envelope fa-lg
      href: contact.html
    - icon: fa-github fa-lg
      href: https://github.com/jsaraviadrago
    - icon: fa-twitter fa-lg
      href: https://twitter.com/statssos
    - icon: fa-linkedin fa-lg
      href: https://www.linkedin.com/in/jcsaraviadrago/
output:
  html_document:
    theme: darkly
    css: 'styles.css'

```
----

  
Pretty simple, the funny thing is that the first icon shows but not the other ones, but the links are still there because when you put the cursor you can actually click on them. 

Thanks a lot!
