### ISSUE TITLE
BUG with pdfcrop and fig_crop in v2.5 => plots not resized properly

### ISSUE THREAD

**Issue by pkR-pkR** [rstudio/rmarkdown#1934]
(Bug checked with cderv) The Rmd example below ~(except the \ before some triple backticks)~(edited) describes a bug/regression introduced in v2.5 (and probably in v2.4) with pdfcrop and fig_crop. In Beamer presentation, the plots are not resized properly anymore in the slide. It is ugly. This is due to the **fig_crop: true** line in the yaml header. The same ugly slides appear if the line **is missing**. Currently, the only solution is to write **fig_crop: false** to get something clean, as in v2.3 and previous versions. 

````
---
title: "A regression in rmarkdown from v_2.3 to v_2.5"
author: "pkR-pkR + cderv"
date: "October 23, 2020"
output: 
  beamer_presentation:
    template: default
    latex_engine: pdflatex
    keep_tex: true
    toc: false
    fig_caption: false
    fig_crop: true
fontsize: 10pt
--- 


# A regression in rmarkdown from v_2.3 to v_2.5

A regression in rmarkdown both on Windows and Debian:

- rmarkdown_2.3.tar.gz properly resizes the following plots
- rmarkdown_2.5.tar.gz badly resizes the following plots

The issue occurs/is linked to pdfcrop:

- Missing line **fig_crop**  in yaml header => BAD
- **fig_crop: true** in yaml header => BAD
- **fig_crop: false** in yaml header => OK

The current default settings break all previous .Rmd files.

Furthermore, pdfcrop on Windows is very slow.

Please, revert to the previous settings (pdfcrop disabled)!

(Bug reproduced by cderv)


# corrplot::corrplot() => OK with v_2.3, Bad with v_2.5

```{r echo=FALSE, message=FALSE, warning=FALSE}
corrplot::corrplot(matrix(runif(900), 30, 30))
```


# lattice::levelplot() => OK with v_2.3, Bad with v_2.5

```{r echo=FALSE, message=FALSE, warning=FALSE}
lattice::levelplot(matrix(runif(900), 30, 30))
```

````

By filing an issue to this repo, I promise that

- [x] I have fully read the issue guide at https://yihui.org/issue/.
- [x] I have provided the necessary information about my issue.
    - If I'm asking a question, I have already asked it on Stack Overflow or RStudio Community, waited for at least 24 hours, and included a link to my question there.
    - If I'm filing a bug report, I have included a minimal, self-contained, and reproducible example, and have also included `xfun::session_info('rmarkdown')`. I have upgraded all my packages to their latest versions (e.g., R, RStudio, and R packages), and also tried the development version: `remotes::install_github('rstudio/rmarkdown')`.
    - If I have posted the same issue elsewhere, I have also mentioned it in this issue.
- [x] I have learned the Github Markdown syntax, and formatted my issue correctly.

I understand that my issue may be closed if I don't fulfill my promises.
