### ISSUE TITLE
Allow .unnumbered .unlisted to ignore header in floating TOC also

### ISSUE THREAD

**Issue by cderv** [rstudio/rmarkdown#1995]
Hi,

I upgraded to Pandoc 2.11.3.1 from 2.9. Applying the class {.unlisted} not working. My section header is still visible in the TOC.
I use:

```
output: 
  html_document:
    theme: spacelab
    toc: yes
    toc_float: yes
    df_print: paged
    number_sections: false
```

and then

```
# Omit this {.unlisted .unnumbered}
```

The "Omit this" section is still visible in the TOC.

_Originally posted by @OliBravo in https://github.com/rstudio/bookdown/issues/894#issuecomment-749473767_
