### ISSUE TITLE
anchor_sections: true doesn't appear to work with runtime: shiny

### ISSUE THREAD

**Issue by cpsievert** [rstudio/rmarkdown#2032]
For example

````yaml
---
title: "My First R Markdown Document" 
runtime: shiny
output:
  html_document:
    anchor_sections: true
---

# R Markdown

## Overview

R Markdown combines markdown (an easy to write plain text format) with embedded
R code chunks.
````
