### ISSUE TITLE
Mysterious @media print {} CSS inserted into R Markdown document (how to remove?)

### ISSUE THREAD

**Issue by davidwales** [rstudio/rmarkdown#2109]
## Minimal Reproducible Example:

1. Create an Rmd document:  
```
---
output: html_document
---

# Test
```
2. Click 'Knit'.
3. Open the knitted report in Firefox
4. Inspect the page, and click the button to 'toggle print media simulation'   
  ![image](https://user-images.githubusercontent.com/55477181/114815133-f272eb80-9df8-11eb-9b16-67b3fea73c6e.png)
5. Notice that following potentially unwanted CSS is added to the page:
``` css
*, ::after, ::before {
    color: #000 !important;
    text-shadow: none !important;
    background: 0 0 !important;
    -webkit-box-shadow: none !important;
    box-shadow: none !important;
}
```

## Comments

So far as I can tell, this CSS is not part of the pandoc template.
Instead, it appears to be added by the option `--include-in-header "~\AppData\Local\Temp\RtmpqekYCZ\rmarkdown-str284036ee5fd4.html"` which is automatically passed to pandoc by R Markdown. However, I can't work out where this file is coming from, or how to disable it.
