### ISSUE TITLE
graphicspath is not working properly

### ISSUE THREAD

**Issue by msgoussi** [rstudio/rmarkdown#2110]
If there is a picture located in images folder (ie D:\\Folder2\\images\\picture1), and x.rmd is located in D:\\Folder1, then when i rund rmarkdown::render("D:\\Folder1\\x.RMD",  output_file =  "x.pdf",  output_dir = "D:\\Folder2", quiet = TRUE), 
I get an error: ! LaTeX Error: File `picture1' not found.

x.RMD
```
---
output: 
  pdf_document: 
    latex_engine: xelatex
    keep_tex: true
header-includes:
- \usepackage{graphicx}
- \graphicspath{{images}}
---
\includegraphics[width=39.5mm,height=20.4mm,keepaspectratio]{picture1}

```

**Comment by cderv** [comment]
Hi ! 

Sorry for the delay answering this one. I needed to find time trying around. 

First, `graphicspath` is working properly as long as no changes  in directory are made in `render()` call. 

For example this should work
````
---
output: 
  pdf_document: 
    latex_engine: xelatex
    keep_tex: true
header-includes:
- \usepackage{graphicx}
- \graphicspath{{D:/Folder2/images}}
---
\includegraphics[width=39.5mm,height=20.4mm,keepaspectratio]{picture1}
````
 if you call like this 
````
rmarkdown::render("D:/Folder1/x.RMD")
````

When using relative path like just `\graphicspath{{images/}}`, it will not behave as expected especially when using `output_dir` or `intermediate_dir`. This is related to other paths issue like #2183

In fact, the rendering of the `.tex` file to PDF will not happen in the `output_dir`, so setting `graphicspath` to a path relative to output_dir won't work. Usually conversion will happen in `intermediate_dir` but that is not so sure. 

We definitely have something to improve regarding paths and were conversion is happening. I'll group this with other similar issues.

For now, best thing with that would be to render everything in current Rmd directory then move the result yourself after the process. 

Thanks for the report.
