### ISSUE TITLE
Flexdashboard in tabs showing up in Safari but not Chrome

### ISSUE THREAD

**Issue by moldach** [rstudio/rmarkdown#2136]
I'm not sure why but an embedded dashboard is showing up in Safari browser but not Chrome (confusing users who open up the documentation with the wrong browser) - any idea how to fix this?

![Screen Shot 2021-05-11 at 4 02 17 PM](https://user-images.githubusercontent.com/5749465/117890511-85753900-b272-11eb-9264-2fcace6da789.png)

## YAML
````yaml
---
title: "Association Model"
author: Matthew Oldach
date: "`r format(Sys.time(), '%Y-%m-%d')`"
output: 
  html_document:
    theme: paper
    highlight: tango
    toc: true
    toc_float: true
---
````

## Tabset example
````markdown
```{r, out.width=900}
knitr::include_app("dashboards/source-flexdashboard.html")
```
````
