### ISSUE TITLE
Is there anyway to view a html document I have created through my Github repo on a browser? 

### ISSUE THREAD

**Issue by TommyH-Tran** [rstudio/rmarkdown#2178]
I have wrote a protocol and have knitted both the github document and html document to a private Github repo. Here is the code I used 

```
---
output:
  html_document:
    toc: true
    number_sections: true
    toc_depth: 4
    toc_float:
      collapsed: false
    self_contained: true
  github_document:
    toc: true
    toc_depth: 4
editor_options: 
  markdown: 
    wrap: 72
---
```
I cannot view the html through the browser because it is too big and can only be viewed in raw format. I personally prefer how the html looks and want my colleagues to be able to view it because of the interactive table of contents. Is there any work around for this? I want my colleagues to be able to go to the Github repository on their browser and easily view it.
