### ISSUE TITLE
[FR] Output format based on Pandoc "defaults file"

### ISSUE THREAD

**Issue by allefeld** [rstudio/rmarkdown#2267]
This is a mixture between a question and a feature request.

In recent versions, Pandoc supports a new command line argument `--defaults=` with which a so-called ["defaults file"](https://pandoc.org/MANUAL.html#default-files) is specified. This file is in YAML format and makes it possible to configure all aspects of the Pandoc conversion process in a single file (apart from the template, which is referenced from the defaults file), i.e. all command line options have YAML equivalents. For example, I have a file `~/.pandoc/defaults/beamer_pdf.yaml` which specifies how I like my Beamer slides to be generated:

````yaml
reader: markdown+hard_line_breaks
writer: beamer
template: modified.latex
pdf-engine: latexmk
pdf-engine-opt: "-pdfxe"
dpi: 72
variables:
  theme: metropolis
  themeoptions:
    - sectionpage=simple
    - numbering=none
    - progressbar=foot
  mainfont: Fira Sans Regular
  mainfontoptions:
    - BoldFont={Fira Sans Medium}
  mathfont: Fira Math
  mathfontoptions:
    - math-style=ISO
    - bold-style=ISO
    - nabla=upright
    - partial=upright
    - Scale=1
  hyperrefoptions:
    - pdfpagemode=UseNone
````

I can now create Beamer slides from a Markdown file with the simple command

````
pandoc --defaults=beamer_pdf.yaml slides.md --output slides.pdf
````

I have several such defaults files for different kinds of outputs.

I recently started using R, and I would now like to use my existing defaults files for R Markdown. The idea would be to create a new output format which could be used like this in the YAML block of an R Markdown file:

````yaml
---
title: xyz
author: abc
output:
  pandoc::defaults:
    file: beamer_pdf.yaml
...
````

Following the instructions in *R Markdown: The Definitive Guide* under [Fully custom formats](https://bookdown.org/yihui/rmarkdown/format-custom.html), my attempt was this; within a package `pandoc`:

````R
defaults <- function(file) {
  rmarkdown::output_format(
    knitr = rmarkdown::knitr_options(),
    pandoc = rmarkdown::pandoc_options(
      args = paste("--defaults", file, sep = "=")
    ),
    clean_supporting = FALSE
  )
}
````

This doesn't work, because the argument `to` of `pandoc_options` needs to be specified. I guess I could replicate the way Pandoc finds defaults files, find it myself, read the YAML and set the argument based on the value of `writer`.

To simulate that, second attempt:

````R
defaults <- function(file) {
  rmarkdown::output_format(
    knitr = rmarkdown::knitr_options(),
    pandoc = rmarkdown::pandoc_options(
      to = "beamer",
      args = paste("--defaults", file, sep = "=")
    ),
    clean_supporting = FALSE
  )
}
````

The resulting Pandoc command is

````
/usr/bin/pandoc +RTS -K512m -RTS test.knit.md --to beamer --from markdown+autolink_bare_uris+tex_math_single_backslash --output test.tex --defaults=beamer_pdf.yaml
````

Several problems:

- A default value of `from` has been used, which conflicts with my setting in the defaults file. I don't mind `autolink_bare_uris` and `tex_math_single_backslash`, but I do prefer to have `hard_line_breaks`. Well, I guess I could extract that, too, and set it explicitly. 

- The output file is specified with extension `.tex` instead of `.pdf`. I tried the argument `to = "pdf"` – then I get a pdf file, but also a `--to latex` command line option.

- The `--defaults` command line argument is at the end, which makes Pandoc ignore it for the most part.

__As a question:__ What do I have to do in order to get the exact necessary Pandoc command to use my defaults file?

__As a feature request:__ In case that proves impossible, I propose that it is made possible.

I am aware that I could probably achieve the equivalent of my defaults files by inheriting from an existing output format and overriding the right options. However, that would mean to duplicate the effort I have already put in my defaults files, and every time I change something in my defaults files I would have to do the corresponding changes in the R code. I'd rather have a simple-to-use output format in R Markdown, the complete behavior of which is defined by the YAML defaults file.

I believe that this might also be useful for other users, because they wouldn't have to create an R package with a custom function, but they would simply write a defaults file.
