### ISSUE TITLE
[FR] github_document Dark HTML Preview

### ISSUE THREAD

**Issue by Amarakon55** [rstudio/rmarkdown#2354]
I use GitHub on my web browser in dark mode. The default HTML preview is white background and black text, but I would like for a dark theme that matches GitHub's dark theme so the preview will be more accurate. Like this:

```yaml
output:
  github_document:
    theme: dark
```
