### ISSUE TITLE
`css` argument of `html_document` doesn't work with `runtime: shiny` + `{bslib}` `theme`

### ISSUE THREAD

**Issue by cpsievert** [rstudio/rmarkdown#2443]
Can reproduce by doing `rmarkdown::run("index.Rmd")` with the following `index.Rmd`

```yml
---
title: "Title"
runtime: shiny
output:
  html_document:
    css: styles.css
    theme:
      version: 5
---

### Another title
```

And `styles.css`:

```css
body {background-color: purple;}
```

Which will generate the following error:

```
Warning in file(con, "r") :
  cannot open file 'styles.css': No such file or directory
```
