### ISSUE TITLE
`css` argument of `html_document_base` doesn't work with `scss/sass` files when `runtime: shiny`

### ISSUE THREAD

**Issue by cpsievert** [rstudio/rmarkdown#2447]
Seemingly for the same reason as https://github.com/rstudio/rmarkdown/issues/2443 (that is, when `runtime: shiny`, `html_document_base()` gets invoked in a temporary directory)

````yaml
---
title: "Title"
runtime: shiny
output:
  html_document:
    css: styles.scss
    theme: darkly
---

### Another title

````

```scss
body {background-color: purple;}
```

Which will generate the following error:

```
Error in sass::sass_file: Could not find file: 'styles.scss' in dir: 
  /private/var/folders/t8/jxw4bftj35g15fcb6m4mfbc80000gn/T/Rtmpg4LF0x
```
