### ISSUE TITLE
How to set the background color on a given slide?

### ISSUE THREAD

**Issue by ignacio82** [rstudio/rmarkdown#250]
How can you set the background color on a given slide?

For example:

```

---
title: "Never put off 'till tomorrow?"
author: "Ignacio Martinez"
date: "09/23/2014"
output:
  ioslides_presentation:
    incremental: yes
    css: ./styles.css
    widescreen: yes
    self_contained: true
    font-import: http://fonts.googleapis.com/css?family=Ubuntu
    font-family: Ubuntu
runtime: shiny

---

# Thomas Jefferson {.background-color: "orange"}

<q>_Never put 'till tomorrow what you can do today_</q>
```
