### ISSUE TITLE
[FR] `yaml_front_matter()` doesn't ignore comments

### ISSUE THREAD

**Issue by willgearty** [rstudio/rmarkdown#2579]
This might be a pretty niche use case here, but here goes anyways...

I use `pkgdown` to generate my package's website, but some of the vignettes often fail to compile when using GitHub actions, so I'm currently precomputing them as described [here](https://ropensci.org/blog/2019/12/08/precompute-vignettes/). This means I have a set of source files that I edit, then generate the precomputed files with a [custom script](https://github.com/palaeoverse/rmacrostrat/blob/main/vignettes/precompile.R) before pushing it all to GitHub to then have pkgdown do its thing.

However, while onboarding some a package contributor, I noticed they were editing the precomputed files instead of the source files. I'll be updating our contributing docs accordingly, but I was also looking into other ways to help ensure these files aren't edited. I recalled the comment headers in .Rd files which are auto-generated by `roxygen2` and which are read by RStudio and provide a handy little warning banner (see https://github.com/rstudio/rstudio/issues/2082 and https://github.com/rstudio/rstudio/pull/2085). I tried adding comments like this (as HTML comments) to the top of my precomputed .Rmd files, like so:

```
<!-- Generated by vignettes/precompile.R: do not edit by hand.
Please edit source in vignettes/source/geologic-map.Rmd -->
```

This worked great, with RStudio showing the expected warning banner and the vignette still knitting fine with `knitr`. However, then when `pkgdown` renders the website, it doesn't read the front matter correctly. I followed the code trail to find that these new comments broke `rmarkdown::yaml_front_matter()` which `pkgdown` uses to get the title of the vignette.

So, I guess my question/request is: is there a way to provide a comment at the top of a vignette that wouldn't cause this issue? If not, could the regex in `rmarkdown:::partition_yaml_front_matter()` (see [here](https://github.com/rstudio/rmarkdown/blob/c787e8a8c96726b4c3430bc53360be5f806bb114/R/output_format.R#L754-L770)) be modified to allow for this?

Alternatively, can anyone think of a different way of triggering the RStudio banner without breaking `knitr` or `rmarkdown`?

**Comment by cderv** [comment]
You should also be able to do this right ? 
````yaml
---
# Generated by vignettes/precompile.R: do not edit by hand. Please edit source in vignettes/source/_rredlist.Rmd
title: "Introduction to rredlist"
author: "William Gearty"
date: "2024-10-01"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Introduction to rredlist}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

````

**rmarkdown** expects document to start with the YAML block to be highlighted and parsed correctly. So I wouldn't add HTML like comment as first line before `---`. 

But you can use comment inside the YAML part. `#` is supported by the parsed, and RStudio IDE will search for the 5 first lines for `do not edit by hand.`. But this feature seems mainly meant for Roxygen as the fallback does not support an alternative matching. 
Full code at: https://github.com/rstudio/rstudio/blob/2175496934a54e21979461a1c67eb13ad5048cf2/src/cpp/session/SessionSourceDatabase.cpp#L258-L305

Modifying the regex to allow more lines before `---` could have bad side effect. This is a constraint and requirement for a long time. Hard to change.
