### ISSUE TITLE
Understanding `_output.yaml` in generating websites

### ISSUE THREAD

**Issue by cboettig** [rstudio/rmarkdown#297]
Pandoc has the very convenient feature of being able to specify an external yaml file to provide metadata that would be re-used across multiple files; as shown in the docs:

```
pandoc chap1.md chap2.md chap3.md metadata.yaml -s -o book.html
```

At first I'd imagined that this is how `_output.yaml` was working too, but at closer inspection it appears that's not the case.  This is rather frustrating as it was very convenient to be able to define arbitrary template metadata in a `metadata.yaml` that I could then use in custom templates (e.g. rather analogous to _config.yaml in Jekyll).  Unfortunately, if I just create an `_output.yaml` like this:

``` yaml
html_document:
  self_contained: false
  css: 
    - http://www.carlboettiger.info/assets/css/bootstrap.min.css
    - //netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css
rss: http://www.carlboettiger.info/blog.xml
rss-title: "Carl Boettiger's Lab Notebook"
site.url: http://carlboettiger.info
analytics: UA-XXXXXX-1 
author: 
  name: Carl Boettiger
  twitter: cboettig
  github: cboettig
```

it seems some variables, like css, are recognized, but arbitrary template variables like `author.twitter` are not (whether or not they are nested under `html_document`).  If instead I run pandoc directly and use the above `yaml` file as an external metadata block like in the `metadata.yaml` case illustrated above, everything works.  Would it be possible for rmarkdown to support something like this?
