### ISSUE TITLE
The default LaTeX template does not work with multiple authors 

### ISSUE THREAD

**Issue by yihui** [rstudio/rmarkdown#353]
A minimal reproducible example:

```yaml
---
title: "R Markdown v2 Demo"
author:
  - John
  - Joe
date: "2015/01/01"
output:
  pdf_document:
    keep_tex: yes
---

Hello world.
```

The error message:

```latex
! Misplaced \crcr.
\endtabular ->\crcr 
                    \egroup \egroup $\egroup 
l.71 \maketitle
```

I have no idea what this means. Perhaps @robjhyndman can help again? Thanks!
