### ISSUE TITLE
citecolor LaTeX option not being used

### ISSUE THREAD

**Issue by fgnu** [rstudio/rmarkdown#362]
I am trying to create a JSS article using RMarkdown, but am not able to get options that [typically get used with `pdf_document`](http://rmarkdown.rstudio.com/RMarkdownReferenceGuide.pdf), in particular, the `citecolor` option.

Here is an MWE, which is the standard JSS template that ships with the `rticles` package:

```

---
author:
  - name: FirstName LastName
    affiliation: University/Company
    address: >
      First line
      Second line
    email: name@company.com
    url: http://rstudio.com
  - name: Second Author
    affiliation: Affiliation
title:
  formatted: "A Capitalized Title: Something about a Package \\pkg{foo}"
  # If you use tex in the formatted title, also supply version without
  plain:     "A Capitalized Title: Something about a Package foo"
  # For running headers, if needed
  short:     "\\pkg{foo}: A Capitalized Title"
abstract: >
  The abstract of the article.
keywords:
  # at least one keyword must be supplied
  formatted: [keywords, not capitalized, "\\proglang{Java}"]
  plain:     [keywords, not capitalized, Java]
preamble: >
  \usepackage{amsmath}
output: rticles::jss_article
citecolor: blue
references:
- id: fenner2012a
  title: One-click science marketing
  author:
  - family: Fenner
    given: Martin
  container-title: Nature Materials
  volume: 11
  URL: 'http://dx.doi.org/10.1038/nmat3283'
  DOI: 10.1038/nmat3283
  issue: 4
  publisher: Nature Publishing Group
  page: 261-263
  type: article-journal
  issued:
    year: 2012
    month: 3

---

# Introduction
[@fenner2012a]

# References
```

This does not highlight the reference to be blue. Do I have to adapt the entire template to change the one parameter?

---

Note: cross-posted from [here](http://stackoverflow.com/questions/28193114/rmarkdown-citecolor-latex-option-not-being-used).
