### ISSUE TITLE
pandoc-citeproc: Macro "access" not found!

### ISSUE THREAD

**Issue by joelgombin** [rstudio/rmarkdown#426]
Each time I'm trying to render an Rmd doc with some bibliographic references from Rstudio, I get the same error:

```
pandoc-citeproc: Macro "access" not found!
pandoc: Error running filter /usr/lib/rstudio/bin/pandoc/pandoc-citeproc
Erreur : pandoc document conversion failed with error 83
Exécution arrêtée
```

The YAML metadata section looks like:

```

---
title: "Estimer les reports de voix"
author: "Joël Gombin"
date: "15 mai 2015"
output: 
  word_document: 
    fig_caption: yes
bibliography: biblio.bib
csl: espacepolitique.csl

---
```

I use Rstudio 0.99.435, R 3.2.0 and rmarkdown 0.6.1, under Ubuntu 14.04. 

When I try to render the source from R CLI, I get `Erreur : pandoc version 1.12.3 or higher is required and was not found.`

Any idea what might be going wrong? I didn't manage to find exacty the same issue online.
