### ISSUE TITLE
include script in source page

### ISSUE THREAD

**Issue by thomasbrand** [rstudio/rmarkdown#455]
I need to include a script in a page. I know the 'includes' option in html_document, but I want to call the script before the head, and not 'in_header', how can I procede ? Thanks!

**Comment by jjallaire** [comment]
For this you probably just need to create your own template (there's no way
to inject code in the head outside of the in_header directive)

**Comment by thomasbrand** [comment]
Thanks, but maybe I must be more precise. 
I work on rmarkdown in a shiny-server. In order to use the iframe-resizer javascript (http://davidjbradshaw.github.io/iframe-resizer/), I have to include the source before the page is executed, so using the 'includes' option in metadata is to late. If I open the html produced by the shiny-server and put by hand the src in the head, it works. 
Do I need to create a www folder with a new index.html, containing the javascript ? It doesn't seem to work.

**Comment by thomasbrand** [comment]
I think I have found the problem, which is similar to #457 in a sense. When I knit locally a Rmd file with only in metadata
```
output: 
  html_document:
    css: "obsmacro_bootstrap.css"
    self_contained: false
    keep_md: true
    includes: 
      in_header: "header_iframe_resizer.html"
```
everything works fine, but when I add `runtime: shiny`, or put the Rmd file in my shiny-server folder, the script included in "header_iframe_resizer.html" doesn't work.
