### ISSUE TITLE
Custom pandoc template with runtime:shiny not working

### ISSUE THREAD

**Issue by lmccusker** [rstudio/rmarkdown#457]
I am unable to use my custom pandoc template in my ioslides presentation if runtime: shiny is included.

This works great:

```

---
title: "Presentation"
output: 
  ioslides_presentation:
    self_contained: false
    template: ./templates/template.html

---
```

But this does not:

```

---
title: "Presentation"
runtime: shiny
output: 
  ioslides_presentation:
    self_contained: false
    template: ./templates/template.html

---
```

I get the following error:

Error : pandoc document conversion failed with error 1
