### ISSUE TITLE
location of \usepackage with lualatex

### ISSUE THREAD

**Issue by stla** [rstudio/rmarkdown#469]
The following metadata generates a problem:

```

---
title: 'brr: Basic usage.'
author: "Stéphane Laurent"
date: '`r Sys.Date()`'
output:
  pdf_document:
    keep_tex: yes
    pandoc_args: --latex-engine=lualatex
header-includes:
   - \usepackage{unicode-math}
   - \usepackage{fontspec}
fontsize: 12pt
mainfont: XITS
mathfont: texgyretermes-math.otf

---
```

The error is: 

```
! Undefined control sequence.
l.20     \setmathfont
```

The problem is that the command `\setmathfont` appears before `\usepackage{unicode-math}` in the `tex` file.
