### ISSUE TITLE
Relative dependencies closer to root than an output html

### ISSUE THREAD

**Issue by jrounds** [rstudio/rmarkdown#472]
This when generating html this yaml errors when the lib_dir line is included (but not when the css line is included, so is it not checked in the same way?)  Which leads to the question is there an rmarkdown idiomatic way to include a lib directory closer to root than the output?  Is there someway to disable the check that errors?  Thanks.

```
---
output:
  html_document:
    theme: readable
    self_contained: false
    css: ../../style.css
    lib_dir: ../../lib
    toc: true
    toc_depth: 2
    date: "`r format(Sys.time(), '%d %B, %Y')`"
---
```
  Error message and call stack
```
> debugger()
Message:  Error in relativeTo(basepath, dir) : 
  The path /media/sf_work/15spring/lib/jquery-1.11.0 does not appear to be a descendant of /media/sf_work/15spring/weake_aging/04_03_edgeR/go_html_reports/GO_0006310/
Available environments had calls:
1: render("11_go_template.Rmd", output_dir = out_dir, output_file = out_file)
2: output_format$pre_processor(yaml_front_matter, utf8_input, runtime, knit_me
3: base(...)
4: pandoc_html_extras_args(extras, self_contained, lib_dir, output_dir)
5: as_tmpfile(html_dependencies_as_string(dependencies, lib_dir, output_dir))
6: html_dependencies_as_string(dependencies, lib_dir, output_dir)
7: lapply(dependencies, makeDependencyRelative, output_dir)
8: FUN(X[[1]], ...)
9: relativeTo(basepath, dir)
10: stop("The path ", file, " does not appear to be a descendant of ", dir)
```
