### ISSUE TITLE
output_dir and yaml for lib directories vs style files.

### ISSUE THREAD

**Issue by jrounds** [rstudio/rmarkdown#474]
I posted an issue yesterday, this one is different.  This is a minor issue about lib_dir vs css fields in the yaml.

Now suppose my Rmarkdown document resides in /tmp, but ultimately I want to use lib and style directories in /tmp/01, and render an html into /tmp/01.  The file and directory structure prior to generating a report are this:

```
/tmp/foo.Rmd
/tmp/01/lib
/tmp/01/style.css
```

The appropriate yaml to get everything working right  (and as far as I know the only yaml) is:
```
---
output:
  html_document:
    self_contained: false
    lib_dir: 01/lib
    css: style.css
---
```

After a call to render("foo.Rmd", output_dir=/tmp/01),  the generated html files will have this in it:
```
<script src="lib/jquery-1.11.0/jquery.min.js"></script>
<link rel="stylesheet" href="style.css" type="text/css" />
```

A more intuitive yaml to me was this because it did not treat lib_dir and css as different relative to the generating .Rmd.
```
---
output:
  html_document:
    self_contained: false
    lib_dir: 01/lib
    css: 01/style.css
---
```
(In actual fact a more intuitive yaml to me was one without 01 because I wanted to think of the files as relative to the html but that isn't how it works.)

But if you do that you end up with html like this:
```
<script src="lib/jquery-1.11.0/jquery.min.js"></script>
<link rel="stylesheet" href="01/style.css" type="text/css" />
```

The issue is that 01 is the directory the html file is in, and that style sheet won't be found.  The point here is the css and lib_dir field have two different relative behaviors when used with output_dir.  I am just letting you know about this counter-intuitive aspect of yamls and rmarkdown render with output_dir that could slow down adoption.
