### ISSUE TITLE
RMarkdown won't recognize both fontsize and mainfont when converting to PDF

### ISSUE THREAD

**Issue by kmiddleton** [rstudio/rmarkdown#513]
An Rmd file with the YAML headers:

```
   ---
    title: "Untitled"
    author: "Me"
    date: "September 14, 2015"
    output:
      pdfdocument:
        latexengine: xelatex
    fontsize: 12pt
    ---
```

Correctly renders in 12 computer modern roman when converted to PDF in RStudio. If I add `mainfont`:

```
    ---
    title: "Untitled"
    author: "Me"
    date: "September 14, 2015"
    output:
      pdfdocument:
        latexengine: xelatex
    fontsize: 12pt
    mainfont: Helvetica
    ---
```

The PDF is rendered in Helvetica, but at 10 point. I can't get PDF output of 12pt non-CMR.

I've also tried setting the YAML to `12pt` and putting `\usepackage{helvet}` in an external `.tex` file that gets included `in_header`, but I get 12pt CMR.

sessionInfo:

```
> sessionInfo()
R Under development (unstable) (2015-09-02 r69271)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.10.4 (Yosemite)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] fortunes_1.5-2 devtools_1.8.0

loaded via a namespace (and not attached):
 [1] rversions_1.0.2 htmltools_0.2.6 tools_3.3.0     yaml_2.1.13     curl_0.9.2      Rcpp_0.12.0    
 [7] memoise_0.2.1   xml2_0.1.1      rmarkdown_0.8   knitr_1.11      git2r_0.11.0    digest_0.6.8
```
