### ISSUE TITLE
CSS Added background image bugged on Windows machine

### ISSUE THREAD

**Issue by martinschmelzer** [rstudio/rmarkdown#525]
Hi there,

when I add a custom background within a custom CSS style sheet it will be properly displayed on my Macbook running OSX10.11 but not on my Windows machine. My custom stylesheet is just the default stylesheet for an ioslides presentation with a modification of the selector at line 242:

``` css
slides > slide {
  display: none;
  font-family: 'Open Sans', Arial, sans-serif;
  font-size: 26px;
  color: #797979;
  width: 900px;
  height: 700px;
  margin-left: -450px;
  margin-top: -350px;
  padding: 40px 60px;
  -webkit-border-radius: 5px;
  -moz-border-radius: 5px;
  -ms-border-radius: 5px;
  -o-border-radius: 5px;
  border-radius: 5px;
  -webkit-transition: all 0.6s ease-in-out;
  -moz-transition: all 0.6s ease-in-out;
  -o-transition: all 0.6s ease-in-out;
  transition: all 0.6s ease-in-out;

  /* MY MODIFICATION */
  background-image: url(Images/logodue.png) !important;
  background-size: 200px !important;
  background-repeat: no-repeat !important;
  background-position: 93.1% 4% !important;
  /* END */
}
```

I therefore added a logo at the top right corner of every slide. Can someone determine why Windows has issues with displaying the logo? I tried 3 different browsers. I assume it has something to do with the base 64 image encoding. But I am not sure.

UPDATE: Displaying the logo is not the problem on Windows. Just knitting the presentation produces the bug in the output HTML file. The presentation is also properly displayed on Windows as long as I knit the it on OSX.

Kind regards,
Martin
