### ISSUE TITLE
Multiple output feature doesn't work

### ISSUE THREAD

**Issue by IamGianluca** [rstudio/rmarkdown#546]
```
title: "Chapter 4, Problem 8 (Gelman & Hill)"
author: "Gianluca Rossi"
date: "6 November 2015"
output: 
  md_document:
    variant: markdown_github
  html_document:
    toc: true
    theme: united
```

The code above should let me create two outputs: an `.md` file and a `.html` file. However, it generates and/or update only the `.md` file. Inverting the order of the outputs, I can update or generate the `.html` file, but not the `.md` file. 

Basically, only the first specified output is considered. 

```
> version
               _                           
platform       x86_64-apple-darwin13.4.0   
arch           x86_64                      
os             darwin13.4.0                
system         x86_64, darwin13.4.0        
status                                     
major          3                           
minor          2.2                         
year           2015                        
month          08                          
day            14                          
svn rev        69053                       
language       R                           
version.string R version 3.2.2 (2015-08-14)
nickname       Fire Safety  
```

I'm using `rmarkdown` 0.8.1
