### ISSUE TITLE
no longer rendering latex in markdown to pdf

### ISSUE THREAD

**Issue by aurielfournier** [rstudio/rmarkdown#621]
RStudio Version 0.99.878
R Version 3.2.3
Windows 10

After I updated to the new version of RStudio my markdown files with latex code in them are no longer rendering correctly.

code such as \textbf{text here} is fine

\newpage also works just fine

but things like 

```latex
\begin{tabular*}{6.6in}{l@{\extracolsep{\fill}}r}
\Huge\textbf{Auriel M.V. Fournier}  \\
PhD Candidate - University of Arkansas - Fayetteville & XXXXXX@uark.edu \\
\href{url_here}{Arkansas Cooperative Fish and Wildlife Research Unit} & 419.XXX.XXXX \\
\end{tabular*}
```

are printed in the document as the code, not as what should be coming from those commands. 

that is with this as my header

```yaml
---
header-includes:
- \usepackage{tabularx}
- \usepackage{hyperref}
output: pdf_document
---
```
