### ISSUE TITLE
toc_float for html_vignette

### ISSUE THREAD

**Issue by brry** [rstudio/rmarkdown#650]
Feature request:  
Im writing my vignette with output: rmarkdown::html_vignette.
Now that there is a floating TOC for html_document, will it also be available for html_vignette?
It would be really awesome to use
```
output: 
  rmarkdown::html_vignette:
    toc: true
    toc_float: true
```
