### ISSUE TITLE
scrollbar shown when highligthing with non-default theme (e.g. pygments) and code_folding

### ISSUE THREAD

**Issue by jjallaire** [rstudio/rmarkdown#654]
With the following metadata:

``` yaml
title: "Untitled"
output:
  html_document:
    highlight: pygments
    code_folding: show
```

Scrollbars are shown under the code chunks:

<img width="745" alt="screen shot 2016-03-23 at 2 52 33 pm" src="https://cloud.githubusercontent.com/assets/104391/13997133/f222b574-f106-11e5-95b4-e0c448697e08.png">

This does not occur for `highlight: default`
