### ISSUE TITLE
Options in _site.yml are overwriting individual .rmd YAML options

### ISSUE THREAD

**Issue by fernandomayer** [rstudio/rmarkdown#689]
When building a website with rmarkdown, in earlier versions (< 0.9.6), I used to have these options in my `_site.yml`:

```
name: "my-website"
output_dir: "."
output:
  html_document:
    toc: true
    toc_depth: 4
    toc_float:
      collapsed: false
      smooth_scroll: false
```

mainly to specify that I wanted a toc in all pages. However, there are some pages that I don't want a toc, so, in the YAML header of such pages I had something like:

```
---
title: "About This Website"
output:
  html_document:
    toc: false
---
```

In earlier versions of rmarkdown, this used to work fine, and pages with this header did not have a toc. Since version 0.9.6 (and one before that, AFAIR), these exact same configuration are not working anymore, *ie*, all pages are rendering with a toc, even those with the YAML header above.

I didn't change any configuration, only updated rmarkdown, and that stopped working. So now, `_site.yml` options are overwriting individual pages options (at least with toc configurations). Is that a desired behavior? If so, what should I change to prevent some pages of rendering a toc?

A fully reproducible example is available here: https://github.com/fernandomayer/rmd-test

Thanks.
