### ISSUE TITLE
Customized title for navbar?

### ISSUE THREAD

**Issue by ijlyttle** [rstudio/rmarkdown#704]
I would like to be able to include a logo in the title field.

 I have a function to generate the html for the title field on a site-by-site basis, and could write a file `_title.html`.

Could it be possible to add the ability to do something like this?

```YML
name: "my-website"
navbar:
  title: 
    file: _title.html 
  type: inverse
  left:
    - text: "Home"
      icon: fa-home
      href: index.html
...
```

I see in the documentation that we can always write `_navbar.html` ourselves. However, I really the idea of specifying the navbar and menu components using YML.

Accordingly, could I take advantage of the (possibly internal) functions within the rmarkdown package to compose the html for the navbar using YML, then interpolate a custom title into the html, then write `_navbar.html`?

Thanks, hopefully the question is not too-unfocused.
