### ISSUE TITLE
multiple level submenu in navbar?

### ISSUE THREAD

**Issue by byzheng** [rstudio/rmarkdown#721]
It seems it is not possible to add multiple level submenu in navbar to render a website. If so, it will be really nice to add this features for complicated website.

This is my example _navbar.yml. A arrow is shown in the second level of menu, but cannot open it.

``` yaml
title: WIKI
type: inverse
left:
    - text: "Home"
      href: index.html
    - text: Menu1
      menu:
        - text: "Menu 1.1"
          href: menu-1-1.html
        - text: "Menu 1.2"
          href: menu-1-2.html
        - text: "Menu 1.3"
          menu: 
            - text: "Menu 1.3.1"
              href: menu-1-3-1.html
            - text: "Menu 1.3.2"
              href: menu-1-3-2.html 


```
