### ISSUE TITLE
Use default css + custom css file in html_vignette()

### ISSUE THREAD

**Issue by FrancoisGuillem** [rstudio/rmarkdown#732]
When using html_vignette as output function in a document, it looks that there is not any straightforward way to use a custom css file in addition to the default css file. 

The only solution I have found is to copy the whole content is to first use `system.file` to locate the file `vignette.css` and then copy the path like that:

``` yaml
output: 
  rmarkdown::html_vignette:
    css: 
    - style.css
    - D:/Users/franguil/Documents/R/win-library/3.2/rmarkdown/rmarkdown/templates/html_vignette/resources/vignette.css
```
