### ISSUE TITLE
'expr' option being added to parameters that use !r syntax

### ISSUE THREAD

**Issue by DianaCesar** [rstudio/rmarkdown#760]
I noticed that when I create a parameter using the !r syntax, an extra option is automatically added to my list of choices when I go to knit the output with parameters. Here is my param:

```yaml
notes:                
      value: "yes"
      choices: !r c("yes", "no")
      input: select
      label: Notes
      multiple: yes
```

When I Knit with Parameters from within RStudio, I see the following options under Notes:

yes, no, expr

Where is the 'expr' coming from? If I create a param that does not include the !r syntax, there is no issue. Example:

```yaml
other: 
      value: first
      choices: [first, second, third]
      input: select
      label: Other
      multiple: yes
```

This displays the following options, as expected:

first, second, third

On a side note, I played around with the 'expr' option and noticed that if you select this option, what comes back for that parameter is all of the available choices you have specified (minus 'expr' itself). Is this a precursor to 'Select All' functionality (which would be a very useful feature)?
