### ISSUE TITLE
Setting multiple default values disables the parameter

### ISSUE THREAD

**Issue by DianaCesar** [rstudio/rmarkdown#763]
When I knit a .Rmd with the following example parameter in the YAML...

```yaml
params:
other:
      value: [first, second]
      choices: [first, second, third]
      input: select
      label: Other
      multiple: yes
```

...I get the following message in the "Knit with Parameters" window:

Note: The following parameters cannot be customized: other

This message only appears when more than one default value is specified in the YAML (as I have it above). If I set the default value to only one item, the selectInput widget appears as expected. Why is it that setting multiple default values for a parameter prevents that parameter from being changed in the "Knit with Parameters" window?
