### ISSUE TITLE
Error for multiples outputs in render_site

### ISSUE THREAD

**Issue by JrEduardo** [rstudio/rmarkdown#793]
I create my webpages with rmarkdown, function `render_site`. But I have problems when I use more outputs in yaml. For example:

**In _site.yml file**

```
name: ""
output_dir: "."
output:
  html_document: default
  pdf_document: default
navbar:
  left:
    - text: Home
      href: index.html
```

**In index.Rmd file**

```
% My title
% EERJ

## R Markdown

This is an R Markdown document. Markdown is a simple formatting syntax
for authoring HTML, PDF, and MS Word documents. For more details on
using R Markdown see <http://rmarkdown.rstudio.com>.
```

Thus, the function `rmarkdown::render_site()` generates the error below 

``` r
Error in (function (toc = FALSE, toc_depth = 2, number_sections = FALSE,  : 
  unused arguments (lib_dir = "site_libs", self_contained = FALSE)
```

I suppose the problem is related to https://github.com/rstudio/rmarkdown/blob/master/R/render_site.R#L195, because the list in `output_options` is unused in different outputs of`html_document`.
