### ISSUE TITLE
Temp files are left on disk

### ISSUE THREAD

**Issue by thongsav-usgs** [rstudio/rmarkdown#819]
Hi, I have not done a thorough review of the code, but we are using rmarkdown as part of a rendering engine for a live web application and are finding that the disk on the servers fill up with rmarkdown files. I have stepped through the code enough just to know that there are instances where tempfile (EG: https://github.com/rstudio/rmarkdown/blob/master/R/html_resources.R#L186) is called, but have not gone further to see if rmarkdown already attempts to clean them up. 

If rmarkdown does not clean up, I would be happy if the temp files were completely hidden from the user and cleaned up in the background, but would also be OK with the option of passing in the directory to use for all tempfile calls.

**Comment by yihui** [comment]
Typically temp files are cleaned up in `on.exit()`, but there might be a few places where we forgot to clean them up. If you can tell us the patterns of these temp files (filenames/content), we may be able to find out where they were created.

**Comment by thongsav-usgs** [comment]
Ah,  I see the on exit line below. The temp files come from the MD file creation 5 lines below the line I linked. I think that explains it. We are running rmarkdown via Rserve, and I don't believe the rserve process would ever exit and trigger that event. 

I imagine this may become a more common pattern as Rserve becomes more common, but it is not an inherent problem with the cleanup strategy you've implemented. 

Let me know if you have other questions about our use case, but I hesitate to ask for specific changes without knowing the full workflow rmarkdown takes.

**Comment by yihui** [comment]
`on.exit()` is executed when the function call is finished, and it does not require the R process to exit.

**Comment by thongsav-usgs** [comment]
Hmm, in that case here are some files left over:
rmarkdown-str<hash>.html
file<hash>
directories called file<hash> with various javascript/css lib files used by our reports

I can confirm that they are created inside the method referenced above.

**Comment by yihui** [comment]
I just submitted a fix in #820 that will clean up the `rmarkdown-str[hash].html` files. I'm not sure what `file[hash]` files/dirs are. Can you install the development version of knitr and the patched version of rmarkdown via

```r
devtools::install_github(c('yihui/knitr', 'yihui/rmarkdown@bugfix/clean-tempfiles'))
```

and see which temp files are still left over? Thanks!

**Comment by thongsav-usgs** [comment]
That did take care of the "-str" files, but I still have one `file[hash]` file and one `file[hash]_files` folder, with bootstrap, highlight, jquery, and navigation libs.

**Comment by yihui** [comment]
Okay, could you provide a minimal, self-contained, and reproducible example that shows the problem after you call `rmarkdown::render()`?

**Comment by thongsav-usgs** [comment]
Here's a simple one to leave a `file[hash]` file. Use an Rmd file with the following and call call `render(the_rmd_file)`:

````
```{r echo=FALSE, warning=FALSE, message=FALSE, results='asis'}
```{r echo=FALSE, warning=FALSE, message=FALSE, dev='svg', fig.height=10, fig.width=13, results='hide'}
````

**Comment by thongsav-usgs** [comment]
Here's how to reproduce the folder containing javascript/css files, we have a default.yaml file with the following contents:
```
xaxs: "i"
yaxs: "i"
tcl: 0.3
mgp: [1.5, 0.3, 0.0]
yaxt: "s"
xaxt: "s"
points:
  pch: 6
  col: "red"
lines: 
  col: "black"
  lty: 1
  lwd: 1
abline:
  col: "grey"
  lty: 1
  lwd: 1
axis:
  at: NULL
  labels: TRUE
  tick: TRUE 
  line: NULL 
  pos: NULL
  outer: FALSE
  las: 1
title: NULL
text: NULL
mtext: 
  las: 0
grid:
  col: "grey"
  lwd: 1
  lty: 2
segments: NULL
error_bar:
  y.high: 0 
  y.low: 0 
  x.high: 0
  x.low: 0
  epsilon: 0.1
arrows: NULL
callouts:
  col: 'black'
bgCol: 
  col: 'lightgrey'


```

run `render(your_rmd_file, intermediates_dir=dir_containing_default_yaml)`
