### ISSUE TITLE
mainfont (and other fonts) issue with xelatex in Rmarkdown

### ISSUE THREAD

**Issue by Courvoisier13** [rstudio/rmarkdown#822]
Hi,
I would like to use a mainfont in a pdf produced by Rmarkdown.
My header is as follows:

```
---
title: "test"
author: "Courvoisier"
date: "3 October 2016"
output: 
  pdf_document: 
    keep_tex: yes
    latex_engine: xelatex
mainfont: Calibri
---
```

This translates into the following tex header file:

```
\documentclass[]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
\else % if luatex or xelatex
  \ifxetex
    \usepackage{mathspec}
  \else
    \usepackage{fontspec}
  \fi
  \defaultfontfeatures{Ligatures=TeX,Scale=MatchLowercase}
    \setmainfont[]{Calibri}
\fi
```

This does not compile. It gives the following error:

> ! Undefined control sequence.
> \fontspec_calc_scale:n ...ec_tmpb_dim }\fp_div:Nn 
>                                                   \l_fontspec_tmpa_fp {\l_fo...
> l.16     \setmainfont[]{Calibri}

Removing the line:
`\defaultfontfeatures{Ligatures=TeX,Scale=MatchLowercase}`

from the .tex file solves the problem and I can compile and the fonts display nicely.

What can I do to remove this line from the default .tex template?

thanks
