### ISSUE TITLE
rmarkdown 1.2 ioslides override custom CSS settings

### ISSUE THREAD

**Issue by cszang** [rstudio/rmarkdown#883]
I have a custom CSS to adhere to my university's CD. With rmarkdown version 1.2, some CSS rules are overridden with the default ones.

E.g., I have

```css
slides > slide {
    font-family: Helvetica, sans-serif;
    font-size: 32px;
    font-weight: normal;
    color: #000;
    background-image: url(img/TUM.png) !important;
    background-size: 80px !important;
    background-repeat: no-repeat !important;
    background-position: 95% 5% !important;
}
```

In the resulting html, only the background-image is respected, everything else is overridden. Downgrading to 1.1 resolves the issue.
