### ISSUE TITLE
Use spin with render_site

### ISSUE THREAD

**Issue by andrewheiss** [rstudio/rmarkdown#892]
Building a site from RStudio runs `rmarkdown::render_site(encoding = 'UTF-8')`, which renders all `.Rmd` files in the root directory. 

It will not render any `.R` files, which ordinarily is fine, since those don't typically produced HTML output. However, `rmarkdown::spin()` can knit any files—including `.R` files—and keeping R scripts as `.R` instead of `.Rmd` [can be advantageous](http://deanattali.com/2015/03/24/knitrs-best-hidden-gem-spin/).

Right now, if a `.R` script is included in a website project (like the minimal one below), it will not get knitted.

```r
#' ---
#' title: "Testing stuff"
#' output: html_document
#' ---

#' Here's some R code
2 + 2
```

It might be helpful to be able to specify a list of knittable files in `_site.yml` or somewhere else so that these non-`.Rmd` files are rendered when the site is built with `render_site()`. It is currently possible to include `.R` files in the built website with the `include:` YAML key, but including files only copies the raw file to the final site and does not render them.

**Comment by andrewheiss** [comment]
i.e., given these three files in a website project:

`index.Rmd`

    ---
    title: "Testing"
    output: html_document
    ---

    Normal Rmd stuff

    ```{r}
    2 + 2
    ```


`spin.R`

```r
#' ---
#' title: "Testing stuff"
#' output: html_document
#' ---

#' Here's some R code
2 + 2
```

`_site.yml`

```yaml
name: "testing"
navbar:
  title: "Testing"
  left:
    - text: "Home"
      href: index.html
    - text: "Spin"
      href: spin.html
# Something like this
spin: ["spin.R"]
```

`render_site()` could create this output:

```
_site/
  index.html
  spin.html
```

**Comment by zeehio** [comment]
@andrewheiss, you may want to try my PR that addresses this issue:

````r
devtools::install_github("zeehio/rmarkdown@feat_render_site_with_params")
````

Then in the file `_site.yml` you add `autospin: true`

````yaml
name: "testing"
autospin: true
navbar:
  title: "Testing"
  left:
    - text: "Home"
      href: index.html
    - text: "Spin"
      href: spin.html
````

And `rmarkdown::render_site()` should render all .R source files that do not start with an underscore `_`.
