### ISSUE TITLE
Problems with nested params in Rmd files

### ISSUE THREAD

**Issue by jsonbecker** [rstudio/rmarkdown#929]
When I add `params` to the top of the default new Rmd file in RStudio like this:

```yaml
---
title: "Untitled"
author: "Jason Becker"
date: "1/2/2017"
output: html_document
params:
  segments: 
    school: "schools"
    fund: "fund_code"
  school_code: "091"
---
```

I consistently get the error:

`Error: no value field specified for YAML parameter 'segments' Execution halted`

This can be removed by not having any nesting (e.g. whatever I name "segments" it has this error, if I remove that line and un-indent `school` and `fund` I have no problem).

I have confirmed that directly reading this text with `yaml.load` works fine:

```r
> yaml.load('params:
+   segments: 
+     school: "schools"
+     fund: "fund_code"
+   school_code: "091"
+ ')
$params
$params$segments
$params$segments$school
[1] "schools"

$params$segments$fund
[1] "fund_code"


$params$school_code
[1] "091"
```

Here's some info:

```
> sessionInfo()
R version 3.3.1 (2016-06-21)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.12.2 (Sierra)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] yaml_2.1.14

loaded via a namespace (and not attached):
 [1] magrittr_1.5    assertthat_0.1  htmltools_0.3.5 tools_3.3.1    
 [5] tibble_1.2      Rcpp_0.12.7     stringi_1.1.2   rmarkdown_1.1  
 [9] stringr_1.1.0   digest_0.6.10   evaluate_0.10  
```

**Comment by jjallaire** [comment]
You have to do it like this:

```markdown
---
title: "Untitled"
author: "Jason Becker"
date: "1/2/2017"
output: html_document
params:
  segments: 
    value:
      school: "schools"
      fund: "fund_code"
  school_code: "091"
---
```

**Comment by jsonbecker** [comment]
That seems inconsistent with the documentation here:

http://rmarkdown.rstudio.com/developer_parameterized_reports.html

```yaml
---
title: "My Document"
output: html_document
params:
  minimum: 
    label: "Minimum:"
    value: 100
    input: slider
    min: 0
    max: 1000
  region:
    label: "Region:"
    value: east
    input: select
    choices: [east, west, north, south]
  data: 
    label: "Input dataset:"
    value: results.csv
    input: file
---
```

Should `data`, `region`, and `minimum` be nested in `value`?
