### ISSUE TITLE
html_document_base with self_contained: false leading to weird behavior

### ISSUE THREAD

**Issue by ramnathv** [rstudio/rmarkdown#984]
The following Rmd, when rendered...

```
---
title: "Document"
author: "Ramnath Vaidyanathan"
date: "2/27/2017"
output: 
  html_document_base:
    self_contained: false
---

## Hello
```

... results in an html file with

```
<h2>Hello</h2>
```

It resembles the output of `html_fragment` and does not have any of the `body`, `html` tags.

Is this expected behavior?
