### ISSUE TITLE
How can I update the source for rmarkdown.rstudio.com?

### ISSUE THREAD

**Issue by briandk** [rstudio/rmarkdown#999]
Right now, rmarkdown.rstudio.com has some errors. I'd love to help fix them, but I don't know where to issue a PR.

## Example Issue

The documentation example for printing dataframes for PDF output is wrong.

### What it should say

```yaml
---
title: "Habits"
output:
  pdf_document:
    df_print: kable
---
```

## What it currently says

```yaml
---
title: "Habits"
output:
  html_document:
    df_print: kable
---
```

<img width="744" alt="2017-03-17-rmarkdown-website-error 03-17-17 5 36 05 pm" src="https://cloud.githubusercontent.com/assets/330036/24063931/33ac0b70-0b38-11e7-8dea-a74c77dd548d.png">
